gnocchixyz/gnocchi

gnocchi/rest/__init__.py, gnocchi/storage/incoming/__init__.py, gnocchi/storage/incoming/_carbonara.py, gnocchi/storage/incoming/ceph.py
This replaces the thread based approach with a faster write operation for the
driver that will support it.
This seems to improve performance by a large magnitude.
(cherry picked from commit d9d472ed70e327f8affeefbd26135e1db2df376c)
=> storage: introduce add_measures_batch for Ceph

doc/source/index.rst
This seems obvious but we never wrote it anywhere.
=> doc: add where to find source code

gnocchi/cli.py
When something wrong occurs in coordinator callback we just print a
warning for deployer.But we should also print the root cause and
retry later to get the correct block_size. Otherwise the worker
will never work on its block and an entire will never been processed.
This change tracks the correctness of the block_size and retries if
this one not synced.
This change can't be backported, because on master this code is gone.
Change-Id: Id3fc343cb1556b94af501344a8b016618cbebce3
=> retry to get block on error

gnocchi/archive_policy.py, gnocchi/tests/functional/gabbits/archive.yaml, gnocchi/tests/test_archive_policy.py
In case granularity is larger than timespan, then the calculated points
are < zero, and since there was no validation of this value an invalid
policy would be created.
This commit fixes that behaviour.
=> archive_policy: Raise Error if calculated points is < 0

gnocchi/cli.py
we don't need access to indexer to build report. skip loading
indexer to save memory and connection.
=> don't load indexer in reporting process

gnocchi/rest/__init__.py
A non existent `ArchivePolicyRuleInUse` exception is catched when deleting an archive policy rule in the `ArchivePolicyRulesController` controller:
```python
@pecan.expose()
def delete(self, name):
enforce("delete archive policy rule", {})
try:
pecan.request.indexer.delete_archive_policy_rule(name)
except indexer.NoSuchArchivePolicyRule as e:
abort(404, e)
except indexer.ArchivePolicyRuleInUse as e:
abort(400, e)
```
This PR adds this missing exception.
=> Remove catching of non existent ArchivePolicyInUse exception

gnocchi/carbonara.py
we only needed to clean v2 objects because it was msgpack serialised
dict.
see commit: 5596bdea4848d0594990a5adde74045637e69431
=> drop unused clean

gnocchi/carbonara.py, gnocchi/tests/functional/gabbits/resource-aggregation.yaml, gnocchi/tests/test_storage.py
If a metric is empty, carbonara raises an IndexError when checking for the data
on grouping since the Pandas timeseries is empty.
Fixes #69
=> storage: fix resample on empty metric

gnocchi/cli.py, gnocchi/storage/__init__.py
for changing sacks and reporter, there is no need to connect to main
storage and initialise a new coordinator. change so we only connect
to incoming driver and do not create a coordinator connection.
=> incoming-only connection

gnocchi/storage/__init__.py
This is always printed even if nothing have to done:
http://logs.openstack.org/44/468844/17/gate/gate-telemetry-dsvm-integration-ceilometer-ubuntu-xenial/8f54c0e/logs/screen-gnocchi-metricd.txt.gz#_Jun_06_09_09_09_101487
Also we have something to do, we already print another more usefull
message:
"Processing measures for b03bed59-d1da-4db0-b9bf-adff3766d2a9"
=> Remove useless debug message

gnocchi/carbonara.py, gnocchi/storage/_carbonara.py
when getting measures spanning multiple object, we currently use
combine_first. we shouldn't need to use combine_first since there
should not be any overlap in indices across measures in object.
because of that we should be able to use append which is faster
because it doesn't need to verify as much.
benchmark combining 5K points is ~7x faster:
timeit.timeit("asdf=ts.combine_first(ts2);asdf=asdf.combine_first(ts3)",
number=1000)
1.601928949356079
timeit.timeit("asdf=ts.append([ts3,ts2])", number=1000)
0.2242450714111328
i'm not not initialising a new Series to work on because it adds
significant overhead
timeit.timeit("asdf=pd.Series();asdf=asdf.combine_first(ts);
asdf=asdf.combine_first(ts2);asdf=asdf.combine_first(ts3)",
number=1000)
5.4795918464660645
=> append rather than combine_first

gnocchi/storage/incoming/file.py, gnocchi/storage/incoming/redis.py, gnocchi/storage/incoming/s3.py
- don't store all metrics and counts in memory if not building detailed
report.
- leverage pipelines in redis
- remove s3 FIXME since i don't think it's true.
=> reduce memory for slim report

tox.ini
Install redis as a test dependency since it is used as a coordination driver in
functional tests (--coordination-driver is passed to pifpaf).
=> tox: add missing redis dep for functional tests

.travis.yml
Since 464cfc9f8469fc7cea4d6987603775009f6cab16 we change the fetcher
configuration to build the doc of stable branch from master.
But that doesn't work when we build the doc from stable branch.
This change should fix that by fetching all refs.
=> travis: fetch all refs for docs

gnocchi/indexer/sqlalchemy.py, setup.cfg
SQLAlchemy now logs a warning if the driver is not correctly set in the URL.
Fixes #56
=> sqlalchemy: be explicit about the PostgreSQL driver

setup.cfg, tox.ini
Some extra dependency in pifpaf are now set as flavors, such as ceph.
=> Install pifpaf with ceph extra

.travis.yml
The standard Travis procedure installs what's in requirements.txt whereas we
don't care. Let's win a few seconds by doing… nothing instead.
=> travis: remove install step

tox.ini
It's already launched and tested by gnocchi.tests.test_bin, and the current
runs output the logfile to stdout which pollutes test output.
=> Remove gnocchi-config-generator from tox

gnocchi/rest/__init__.py, gnocchi/tests/functional/gabbits/history.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/test_rest.py
=> Return new metrics when creating metrics for a resource

.testr.conf, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/indexer/sqlalchemy/test_migrations.py, gnocchi/tests/test_archive_policy.py, gnocchi/tests/test_bin.py, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_storage.py, run-func-tests.sh, setup.cfg, tox.ini
Oslotest is OpenStack specific and we actually don't use any of its feature
except stdout redirection and log silencing, which is really provided by
`fixtures' and `daiquiri'.
Remove it and use testtools directly. This avoids having OS_* variables used
everywhere and makes sure we don't pull dependencies we don't need (mox3,
os-client-config, etc).
=> Remove oslotest dependency

run-tests.sh
Without pid, wait always return 0.
This change tracks pids to ensure we have the return code
of the background jobs.
=> tests: don't use wait without pid

doc/source/architecture.rst, gnocchi/archive_policy.py, gnocchi/tests/base.py, releasenotes/notes/lighten-default-archive-policies-455561c027edf4ad.yaml
This reduces by one or two thirds the default archive policies CPU
consumption for 'low' and 'medium' by removing one or two definitions.
Also make it clearer that using low and medium is going to be fasten in
terms of CPU as the consumption depends on the number of definition in
an archive policy.
Change-Id: Iaba3b2ef88858ad777147d2859180d9a27658f1c
(cherry picked from commit 246b7873b413418bc244daba6a424f27f5f26e01)
=> archive_policy: lighten the default archive policies

gnocchi/rest/app.py
Add Docker compose support
rest: make sure we use an absolute path for api-paste file
=> rest: make sure we use an absolute path for api-paste file

gnocchi/tests/base.py, gnocchi/tests/test_bin.py
test: don't print the whole config file
tests: hide useless rados output
=> Pull request for sileht/ceph-log-hide

.gitignore
This directory is created by tox when running one of the upgrade test.
=> Add upgrade directory to gitignore

gnocchi/storage/__init__.py, gnocchi/storage/_carbonara.py
gnocchi.rest actually expects storage.SackLockTimeoutError so it currently is
not caught.
=> rest: move _carbonara.SackLockTimeoutError to storage

gnocchi/cli.py
close_services() closes e.g. the coordinator in the MetricProcessor. But
currently it is close before the shutdown is complete, and it's possible that
the processing of metrics requires the coordinator. On shutdown, this can lead
to a backtrace such as:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/cotyledon/_utils.py", line 84, in exit_on_exception
yield
File "/usr/local/lib/python2.7/site-packages/cotyledon/_service.py", line 139, in _run
self.run()
File "/Users/jd/Source/gnocchi/gnocchi/cli.py", line 134, in run
self._run_job()
File "/Users/jd/Source/gnocchi/gnocchi/cli.py", line 242, in _run_job
lock = in_store.get_sack_lock(self.coord, s)
File "/Users/jd/Source/gnocchi/gnocchi/storage/incoming/_carbonara.py", line 77, in get_sack_lock
return …
=> cli: fix close_services() order

tox.ini
Putting `envdir = upgrade` makes tox create an upgrade in the middle of the
source directory, which is not convenient/standard and gets scanned by e.g.
flake8. Let's each job use its own default directory.
=> tox: don't specify envdir

gnocchi/indexer/sqlalchemy.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_indexer.py, gnocchi/tests/test_storage.py
Closes #119 
For some storage drivers I am not really sure what information would be suitable to display in the logs, since I haven't really started using them.
For the indexer and file storage I now get this message:
```
2017-06-16 09:40:05,734 [7284] INFO gnocchi.cli: Upgrading indexer SQLAlchemyIndexer: postgresql://gnocchi:gnocchi@127.0.0.1/gnocchi
2017-06-16 09:40:05,881 [7284] INFO gnocchi.cli: Upgrading storage FileStorage: /home/ubuntu/gn
```
=> Improve indexer and storage INFO logs

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/__init__.py, gnocchi/tests/functional/gabbits/batch-measures.yaml, releasenotes/notes/bulk-metric-get-e2b298478b679087.yaml
support ability to get multiple metrics based on id. returns result
with format matching:
{'id1': [(timestamp, granularity, value)],
'id2': [(timestamp, granularity, value)]}
Fixes: #87
=> batch GET metric interface

gnocchi/rest/__init__.py, gnocchi/tests/gabbi/gabbits/aggregation.yaml
The exception is not caught currently, making the REST API return a 500 error.
Fixes #148
(cherry picked from commit 85c08b4f90d9b9ce0906ae4fe20867526d6c207f)
=> rest: return 404 when granularity does not exist

tox.ini
We have a dedicated tool that can be run in any standard installation of
Gnocchi, not need for a hackish tox target anymore.
=> Remove genconfig target

gnocchi/utils.py
Tooz actually wants ASCII bytes and not random bytes.
Fixes #130
(cherry picked from commit e749b60f49a4a3b48cc5da67a797f717dd8cd01d)
=> utils: use ASCII bytes as member id

gnocchi/cli.py, gnocchi/service.py
`gnocchi-upgrade' and `gnocchi-change-sack-size' are both command line tools
and not daemons. That means they should always log to stderr, and not use the
configuration file instructions as where to log.
Fixes #16
=> Make command line tools log to stderr

gnocchi/storage/incoming/swift.py, run-func-tests.sh
We currently set the number of sack already configured instead of the
asked number. Making upgrade fail when the number of sack is not yet
set.
This change fixes that.
=> swift: we must use the number of default sack

gnocchi/storage/_carbonara.py
we might defer metric deletion if sack is locked. add another
log when actually completed.
=> log metric deletion on completion

doc/source/operating.rst, gnocchi/cli.py, gnocchi/opts.py, gnocchi/rest/app.py, gnocchi/rest/gnocchi-api, gnocchi/rest/wsgi.py, releasenotes/notes/gnocchi-api-uwsgi-f16d958cb26ad90e.yaml, setup.cfg
As the wise Mehdi once said: "nobody reads documentation".
Everybody wants to run a daemon for the API server and everybody wants to run
`gnocchi-api'. Then let's provide it as a wrapper around uwsgi, so it's a fast
and performant HTTP by default.
=> Make gnocchi-api wrap uWSGI

gnocchi/tests/functional/fixtures.py
The incoming driver created by Gabbi fixtures is not passed to the created WSGI
app. While it works anyway (the conf object is passed and used to re-recreate
that incoming object) it's faster to re-use the same object. Let's do that.
=> tests: pass incoming driver to load_app() in Gabbi tests

gnocchi/storage/incoming/ceph.py, gnocchi/tests/gabbi/gabbits/aggregation.yaml, run-tests.sh
We don't have clue for now, but when rados_osd_op_timeout is set,
aio_read seems to return corrupted data or the add_measures callback
does not work as expected.
This change moves back to the synchronous read of the measures like in
3.0.
This code is gone in 4.0 and later, because we use omap attributes
instead.
=> ceph: Remove the async read of incoming measures

doc/source/install.rst
Nothing's gonna work with just "pip install gnocchi" anyway.
=> doc: do not specify just `pip install`

gnocchi/tests/test_utils.py, gnocchi/utils.py
This leverages numpy and datetime64 types rather than pandas.
Let's make this part of the ongoing process of getting rid of Pandas at
somepoint.
=> utils: rely on numpy rather than Pandas to handle timestamps

doc/source/rest.j2
not setting a boundary on aggregates results in some unpredicatable
behaviour. make it a bit more clear what is happening and potential
risks
=> document open-ended aggregation behaviour

gnocchi/cli.py
This makes sure we can encode the sack number on a short unsigned integer.
=> incoming: set maximum number of sacks to 65535

gnocchi/cli.py, gnocchi/opts.py
If you poll e.g every 60s, there's no need to get the member list and update
the partitioner every 30s. Actually the partitioner status should be updated
just before requesting the stack, that'll be perfect.
So let's do that!
=> Remove worker_sync_rate option

gnocchi/cli.py, gnocchi/common/swift.py, gnocchi/indexer/__init__.py, gnocchi/indexer/alembic/env.py, gnocchi/rest/app.py, gnocchi/statsd.py, gnocchi/storage/_carbonara.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/indexer/sqlalchemy/test_migrations.py, gnocchi/utils.py, tools/measures_injector.py
indexer: remove connect() method
Only retry connection to external components in metricd
utils: do not return coordinator id
cli: limit scope of error catching
cli: use MetricProcessBase _configure method to get drivers
=> Pull request for swift-retry-only-metricd

gnocchi/cli.py, gnocchi/storage/common/swift.py, gnocchi/utils.py
Currently storage such as Swift will retry forever to connect on __init__.
Actually, the only process that wants to retry indefinitely is metricd. The API
will keep the client connected forever if it does not raise a 500 error soon
enough.
This patches make sure that the only part retrying for ever is metricd: the
rest (e.g. the API) will fail fast if anything bad happens.
Fixes #194
(cherry picked from commit a64fe4e0f271e5075b4922135e8b2bae293f1f76)
=> Only retry connection to external components in metricd

gnocchi/storage/_carbonara.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
This avoids comparing strings and keep it to timestamp comparison everywhere.
=> storage: return SplitKey objects when listing split keys

gnocchi/carbonara.py, gnocchi/storage/_carbonara.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
SplitKey already carries the sampling, so let's use it rather than passing it
around each time.
This also avoids passing the SplitKey as a simple string and pass the object
around, which is more solid.
=> carbonara: use sampling from SplitKey

gnocchi/carbonara.py, gnocchi/storage/_carbonara.py, gnocchi/tests/test_carbonara.py
The start/key argument is always a SplitKey object, so there's no need to pass
any sampling around. Just simplify the signature.
=> carbonara: simplify unserialize

doc/source/rest.j2, gnocchi/archive_policy.py, gnocchi/carbonara.py, gnocchi/storage/_carbonara.py, gnocchi/tests/functional/gabbits/archive.yaml, gnocchi/tests/functional/gabbits/metric-derived.yaml, gnocchi/tests/test_archive_policy.py, gnocchi/tests/test_carbonara.py, releasenotes/notes/rate-archive-policy-74888634f90a81e3.yaml
This change allows to compute the rate of change before applying
the aggregation method. To do so, aggregation method need to be
prefixed by "rate:"
=> Add rate of change aggregation methods

gnocchi/aggregates/moving_stats.py, gnocchi/archive_policy.py, gnocchi/carbonara.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/json.py, gnocchi/rest/__init__.py, gnocchi/storage/__init__.py, gnocchi/storage/_carbonara.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/base.py, gnocchi/tests/functional/gabbits/archive.yaml, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_archive_policy.py, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_indexer.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py, gnocchi/utils.py
This replaces various weak data type (e.g. integers for sampling are replaced
by numpy.timedelta64) by native numpy data types.
Pandas data types are replaced by numpy data types where possible.
Change-Id: I923d5d4fedf571deb4dac74a72cdd539c51cc5a9
=> carbonara: use numpy native types for computing

gnocchi/service.py
A typo makes the syslog output not working.
This fixes that.
=> logging: fix syslog output

gnocchi/carbonara.py
Pandas handles numpy.datetime64 naturally.
=> carbonara: remove useless calls to pandas.to_datetime

gnocchi/carbonara.py
numpy.frombuffer can have offset/count kwargs, so no need to copy the
uncompressed string around.
=> carbonara: speed up BoundTimeSerie.unserialize by leveraging frombuffer

gnocchi/storage/__init__.py
This should be faster and consume less memory… and work in the same way!
=> storage: use a namedtuple for Measure

gnocchi/carbonara.py
`numpy.frombuffer` offers `count` and `offset` kwargs, so using them should be
enough to avoid a string copy and make things way faster.
=> carbonara: speed up AggregatedTimeSerie.unserialize by using frombuffer

gnocchi/carbonara.py, gnocchi/storage/_carbonara.py
Only a few `numpy.frombuffer` calls are covered by `try/except ValueError`
blocks, whereas they should all be covered and raise InvalidData in case of
error.
=> carbonara: correctly handle all frombuffer errors

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
there is no scenario in normal workflow which requires us to
truncate on init. when loading, the boundedserie should already
be truncated when it was saved. truncating on init seems to
only support a corrupted scenario.
this improves unserialise perf by ~30x... or ~6x compared to v4.0
disclaimer: improvement is so high mainly because _truncate has
to truncate a lot in the benchmark path.
=> BoundedSerie: don't truncate on init

gnocchi/carbonara.py
aggregated ts generation cannot be the same as bounded ts because
aggregated ts has to follow sampling cadence where as bounded ts
has no cadence. because of that the results from aggregates benchmarks
are wrong.
revert to something similar to before but still generate timestamps
only once.
=> fix benchmark data generation

gnocchi/carbonara.py
I don't like reading nanoseconds in second units. Print op/s.
=> carbonara: print AggregatedTimeSerie benchmark result in op/s

gnocchi/storage/ceph.py
The path name that is built is the old pre-v3 name, which should not existed
since it has been migrated. Use the right method to delete the unaggregated
timeseries.
=> ceph: correctly delete the unaggregated timeserie

gnocchi/service.py
(cherry picked from commit 687cff173ac1da583b4ce0f8d959b4f30507cd50)
=> fix syslog_log_facility option spelling

gnocchi/incoming/_carbonara.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py
This read the incoming measures as a Numpy array ready to be sent to Carbonara,
rather than a list that needs a cast.
=> incoming: return directly a Numpy array of measures

gnocchi/carbonara.py
in an aggregatedtimeserie, all timestamps should be some multiple
of the sampling. therefore, doing numpy.floor is useless since if
it's not a clean divide, then the data is corrupt.
also, it doesn't matter anyways because we cast to integer anyways
which is equivalent to the floor. so corruption is hidden anyways
\o/
edit: i used 'anyways' a lot in this commit message...
=> carbonara: don't need floor divide during serialization

doc/source/rest.j2, gnocchi/rest/__init__.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/test_rest.py, releasenotes/notes/mandatory-boundaries-for-overlap-af28dc1e0946c500.yaml
if no boundary is set, the returned series does not necessarily
honour the overlap value. change behaviour so we require a boundary
if overlap is not 100%.
Fixes: #17
=> enforce boundaries on overlap

gnocchi/carbonara.py, gnocchi/incoming/__init__.py, gnocchi/storage/_carbonara.py, gnocchi/tests/test_carbonara.py
we store new measures as array with ('timestamp', 'value') label,
so we can use them as index. this is makes things more obvious and
is faster.
also, use searchsorted instead of linear searching to remove too old timestamps
Fixes: #99
=> use numpy datatype

gnocchi/tempest/scenario/__init__.py
Apparently our CI does not check for tox -e pep8.
=> Fix pep8 with file()

gnocchi/utils.py
to_timedelta naturally uses numpy.timedelta64 but gets cast to
pandas[1]. just make it return numpy.
[1] https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_timedelta.html
=> make to_timedelta return numpy

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/test_indexer.py
When we use the ne operator, row with NULL values are not returned by
mysql or postgresql.
This change fixes the sql query to return them.
Closes #224
(cherry picked from commit 051b11abb41b239a1873e4009d0a6625795f1f76)
=> indexer: fix ne operator

gnocchi/rest/gnocchi-api
Otherwise
Aug 26 01:04:04 rhev-a24c-01 systemd: openstack-gnocchi-api.service:
Failed at step EXEC spawning /usr/bin/gnocchi-api: Exec format error
The unit file is like
[Service]
ExecStart=/usr/bin/gnocchi-api -- --log-file /var/log/gnocchi/api.log
=> Add #!/usr/bin/python to gnocchi-api

gnocchi/rest/__init__.py, gnocchi/tests/gabbi/gabbits/search.yaml
Some operators accept a list or a dict at rest layer, when it should
accept only an attribute value, like bool, str, None.
For Postgresql, that result to an sql error, turned in HTTP 500.
For Mysql, the request succeed with some magic casting.
Closes #240
(cherry picked from commit cd093e4641a202c720ec8b54e335cc91a07f97ca)
=> rest: Fix invalid query validation

gnocchi/rest/app.py, gnocchi/rest/gnocchi-api, gnocchi/rest/wsgi.py
gnocchi.rest.app imports gnocchi.service
gnocchi.service imports gnocchi.opts
gnocchi.opts imports gnocchi.rest.app
Break that cycle so gnocchi.rest.app stops importing gnocchi.service
Closes #294
=> Fix circular dependency on import

gnocchi/utils.py, requirements.txt
pytimeparse was used before switching entirely the parsing to Pandas, which was
already in use. Since we're trying to get rid of Pandas, pytimeparse looks like
the best alternative out there to parse the time span.
Improves #61
=> Use pytimeparse to parse time span

.travis.yml
Pushing git tag will now be enough to push a release to PyPI.
=> Push tag to PyPI using Travis

gnocchi/storage/_carbonara.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/swift.py
metricd scheduler learns about which metrics to process by calling
`list_metric_with_measures_to_process(size, part)`.
The problem currently is that list_metric_with_measures_to_process() uses
(size, part) to poke holes into a list of _measures_, which are very likely to
be ordered by the name of the measure file (true at least for file and ceph
drivers). That means that if the backlog is something like:
[ metric1_measure1, metric1_measure2, … metric2_measure1, metric2_measure2, …]
and if metric1 has e.g. 100k measures to be processed, then all schedulers will
poke holes starting from the beginning of the backlog:
scheduler1 backlog:
[ metric1_measure1, metric1_measure2, … metric1_measure256 ]
scheduler2 backlog:
[ metric1_measure257, metric1_measure258, … metric1_measure512 ]
which is …
=> storage: fix metric processing scheduling inefficiency

doc/source/configuration.rst, gnocchi/cli.py, gnocchi/opts.py
Change default processing delay and tasks per worker
metricd: expose tasks_per_worker as a config option
=> Pull request for stable-3.1-task-per-worker

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
we don't need to truncate for most scenarios.
- from_grouped_serie doesn't need to be truncated because it's
based on bound_series which definitely doesn't need to be truncated
- from_data is used to grab from storage but there is no point
truncating here as don't check max_size when doing so. (we may want to)
- from_timeseries needs to truncate as that's what used to return
results
=> don't blindly truncate on init

.mailmap
This dude uses two different names in the git log, confusing git-log and other
tools as there was two different authors.
=> Add Gordon Chung to .mailmap

gnocchi/indexer/sqlalchemy.py, gnocchi/rest/__init__.py, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search.yaml
Currently we can write {"id": []}. This query doesn't make sense it will
always return an empty list and it's obviously a input error.
This change returns 400 is this case.
=> rest: don't allow empty in

requirements.txt, setup.cfg
Since all drivers are based on Carbonara and there's no (more) plan to not do
that, this patch simplifies dependency by requiring tooz and lz4 as base
requirements.
=> Simplify dependencies by requiring Carbonara

.github/ISSUE_TEMPLATE.md
This will make sure they are reminded to provide accurate and complete
information.
=> Add an ISSUE_TEMPLATE for users opening GitHub issues

gnocchi/rest/api.py
We don't need to query the resource tables when we fetch measures.
This change removes the query to the resource table in this case.
=> rest: don't load useless resource

tox.ini
By default, daiquiri output is hidden. The side effect is
that some sphinx error are not printed.
This change fixes that.
=> doc: enable logging

tox.ini
This change adds -W to sphinx-build and fixes the only warning we have.
The goals is to be able the enable it later on the multi versions build.
=> doc: Enable warning as error

tox.ini
The rest page of the stable branch is missing
We remove retrying from our deps, but miss to put it in docs-gnocchi.xyz
This change fixes that.
=> Fix old doc build

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/metric-list.yaml, gnocchi/tests/test_rest.py
The current metric listing on /v1/metric does not enforce correctly the
attribute filtering on the creator field when the user is non-admin.
That means the attr_filter is empty and a non-admin can actually list all
metrics for all users.
This fixes that by setting the filter correctly.
=> rest: fix ACL enforcement for non-admin on metric list

gnocchi/tests/test_rest.py
This cherry picks commit 2be95704a18229e4d05e57dd3e96de489a16e61d from master
with just test that makes sure ACL rules are OK for metric listing.
=> rest: add test for ACL enforcement for non-admin on metric list

gnocchi/cli.py
Right now if the indexer or storage is not reachable/functioning, the process
crashes and cotyledon restarts it without any delay, which causes hammering the
e.g. storage.
This leverages the retry.utils decorator to retry in a less aggressive manner
to reconnect to storage.
=> cli: retry less aggressively if metricd can't connect to storage

gnocchi/cli/api.py, gnocchi/opts.py, gnocchi/rest/gnocchi-api, gnocchi/rest/wsgi.py, gnocchi/service.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/utils.py
we should only load and setup policy and CORS when preparing
the API service.
=> load api modules only when needed.

doc/source/grafana.rst
Update installation documentation to use the new version of the grafana plugin
=> Doc: update deprecated grafana plugin source

doc/source/glossary.rst, doc/source/index.rst, doc/source/rest.j2
related #340 
Both 'timeseries' and 'time series' are used. And after some research,
I found that 'time series' is used more frequently.
All 'timeseries' are changed to 'time series'.
=> Fix doc word inconsistency

gnocchi/tests/functional/fixtures.py
storage.process_background_tasks() was originally locks each metrics it
processes. But since we move to the sack system the locks are handled by
the caller.
So, the fake-metricd thread of gabbi does not lock metric is process
anymore. This can lead to race when an API call use refresh=true and
metricd also try to process the same metric.
This change fixes that by also using refresh_metric in the fake metricd
used in gabbi tests.
Closes-bug: #244
=> Fix fake metricd used in gabbi

doc/source/rest.j2, gnocchi/carbonara.py, gnocchi/rest/transformation.py, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_transformation.py, releasenotes/notes/support-rolling-transfrom-a12ab4fb4aa8168f.yaml
this implements rolling aggregates which works similar to how
pandas rolling works but more trivial. this differs from deprecated
moving_average by correctly matching points to trailing timestamp
rather than leading timestamp.
it does not return the NaN values that result in shift in values.
#186
=> supporting rolling aggregates

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/indexer/__init__.py, gnocchi/indexer/sqlalchemy.py, gnocchi/rest/api.py, gnocchi/rest/policy.json, gnocchi/tests/functional/gabbits/archive-rule.yaml, releasenotes/notes/add_update_archive_policy_rule-c2ac6b989a3138db.yaml
It is now possible to change the name of an archive policy rule.
Closes #374
=> Allow to rename archive policy rules

doc/source/rest.j2
close #386 
In api usage, add note that it is not possible to modify
metric after creation.
=> Doc - add note regarding metric modification

gnocchi/cli/metricd.py, gnocchi/common/redis.py, gnocchi/incoming/__init__.py, gnocchi/incoming/redis.py, gnocchi/storage/redis.py, gnocchi/tests/base.py, gnocchi/tests/test_incoming.py, gnocchi/utils.py
incoming: add iter_on_sacks_to_process support for Redis
Add notification mechanism in incoming driver to be used by metricd worker
cli: add a wakeup() method to stop process waiting if needed
cli: rename _get_tasks to _get_sacks_to_process
=> Add support for sack notification on incoming driver

doc/source/rest.j2, gnocchi/json.py, gnocchi/rest/cross_metric.py, gnocchi/tests/test_cross_metric.py
use numpy instead of pandas to compute cross metric
- find all the unique timestamps
- create a AxB pre-filled grid where
- A is number of series, and B is length
- if fill, fill as appropriate
- if not fill
- if needed_overlap > 0, compute overlap
- reset start/end boundaries if not provided to first/last
times which overlap all series.
- aggregate as needed.
=> numpy instead of pandas cross-metric

gnocchi/rest/cross_metric.py, gnocchi/tests/test_cross_metric.py
if empty series are cross computed, it should say there's no overlap
rather than an empty result. (unless needed_overlap=0)
=> always return no overlap if there's no overlap

tools/gnocchi-archive-policy-size.py
Force to specify the number of agg methods in archive policy size tool
Fix gnocchi-archive-policy-size with recent Numpy switch
=> Pull request for fix-ap-size-tool

gnocchi/cli/metricd.py
The condition for re-adding the sack on failure has been put under finally by
mistake, rather than under the except block.
Fixes #397
=> metricd: only re-add sack to be processed on failure

gnocchi/cli/metricd.py, requirements.txt
With the new notification system calling _get_sack_to_process as often as each
notification is received, the tooz `run_watchers` function is called too often,
hitting the backend a lot, often for no change.
This patch restores back the previous behavior of updating the list of sack to
process every `metric_processing_delay` maximum. In order to do that, it simply
leverages cachetools and cache the output for a defined TTL equals to
`metric_processing_delay`. That avoids trying to be too smart about when/how to
call run_watchers while giving the wanted result.
Closes #406
=> metricd: cache sacks to process

gnocchi/cli/metricd.py, gnocchi/storage/__init__.py, gnocchi/tests/base.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_rest.py, gnocchi/tests/test_statsd.py
The function does nothing anymore, just wraps process_new_measures. Remove it.
=> storage: remove process_background_tasks

doc/source/install.rst, setup.cfg
operate_aio_write_op have been added on Ceph 12.2
Closes #412
=> rados: Bump min version

gnocchi/cli/metricd.py, gnocchi/incoming/__init__.py, gnocchi/incoming/redis.py, gnocchi/tests/test_incoming.py
The current behavior is to notify no matter what as soon as a new measure is
push into a metric, and therefore, into a sack.
This patches modifies this behaviour by having the measure storage putting a
flag into a special key named after the sack it is pushing into. Metricd
processes watches for this key to be set and get a notification _only the first
time it is set_. Once metricd finishes processing that sack, it delete the key
so it can get notified again if any new measures has arrived.
This patch also simplifies the notification processing in metricd by just
setting back on the notification system when processing is finished. Previous
version was trying to re-enable notification prior to processing but it just
complicates the workflow for little gain; there's no lock around …
=> redis: do not emit notifications until sack is processed

gnocchi/cli/metricd.py
Currently, not all metricd processes handle errors the same way: some
try/except Exception in the same way (janitor, reporting) but some don't
at all (processing).
This factorizes so they all get the same proper error message. That also fixes
a potential hammering bug in the processing reporter. Currently, if any
unexpected exception is raised in the processing job, the run() method raises
back to Cotyledon which restarts the process right away without delay. If the
exception keeps occurring, that can induce an infinite loop.
By catching the exception around _run_job(), interval_delay is respected.
=> metricd: factorize error handling in _run_job

gnocchi/service.py, gnocchi/storage/__init__.py
The current value of 1 is not the optimal setting by default, spreading on the
number of available CPU is likely to have better results to avoid being I/O
bound.
=> Set a correct default value for aggregation_workers_number

gnocchi/cli/manage.py, gnocchi/incoming/__init__.py
Accessing NUM_SACKS and having SackDetectionError is the mechanism that
upgrade() uses to detect if it needs to do its job. But since logging is down
too low-level, the error message is print on the first call of gnocchi-upgrade,
which does not make any sense. Log only where it makes sense.
=> incoming: fix logging on SackDetectionError

gnocchi/rest/aggregates/operations.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/test_aggregates.py
This changes make aggregated() method more generic.
Related #419
=> aggregates: make aggregated() extensible

gnocchi/opts.py, gnocchi/rest/aggregates/processor.py, gnocchi/service.py, gnocchi/storage/__init__.py, gnocchi/tests/test_utils.py, gnocchi/utils.py, releasenotes/notes/parallel_operations_replaces_aggregation_workers_numbers-cb3a8cf62211bd5b.yaml
The option storage.aggregation_workers_number is not only used by storage, but
also by API cross aggregation. Make it generic and move the map_in_thread
method in a generic parallel_map function in gnocchi.utils.
=> Rename storage.aggregation_workers_number to parallel_operations

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/exceptions.py, gnocchi/rest/aggregates/operations.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-fetch.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/test_aggregates.py, releasenotes/notes/aggregates-API-d31db66e674cbf60.yaml
This changes implements the following operations for the aggregates API:
- rolling <agg> <window>
- resample <agg> <granularity>
- math (*/+-%...)
- abosolute/negative
It also re-add transformation tests related to metrics endpoint
but with new aggregates API.
Related #419
=> aggregates: implements more operations

gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py
"resample" can be done within the "operations".
This change does that.
=> aggregtated: remove useless resample argument

gnocchi/rest/aggregates/processor.py
instead of for every single metric (even though they are in same
matrix)
=> transpose once

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric.yaml, releasenotes/notes/aggregates-API-d31db66e674cbf60.yaml
This change adds the /v1/aggregates/search-and-fetch API.
It allows to search for metrics with the same format as
resource search and cross metric aggregation.
And then it applies operations on them like /v1/aggregates/fetch API.
It also re-add transformation tests related to cross metric aggregation
endpoint but with new aggregates API.
Related #419
=> aggregates: search-and-fetch api

gnocchi/cli/manage.py, gnocchi/cli/metricd.py, gnocchi/rest/app.py, gnocchi/storage/__init__.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_storage.py, gnocchi/utils.py
This forces the storage driver to receive a coordinator as parameter.
=> storage: do not create coordinator oneself

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml
we explicitly take first and last timstamps common across all
series as the boundaries if missing.
=> remove boundary requirements

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml
It's not necessary useful to forbid fill without granularity.
Of course, some "operations" doesn't make sense. Like resample without
granularity. But it's up to the user to understand that.
=> aggregates: remove useless checks

doc/source/rest.j2, gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml, releasenotes/notes/fill=dropna-9e055895e7bff778.yaml
dropna is like null but nan values are not returned.
This is the default for /v1/aggregates API.
This also change our json dumps() to handle nan and return null instead.
=> aggregates: new fill=dropna

devstack/plugin.sh, gnocchi/cli/metricd.py, gnocchi/opts.py, gnocchi/rest/app.py, gnocchi/service.py, gnocchi/storage/__init__.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py
The coordination url is more used by the incoming driver for sacks than for the
storage. It has been there fore historical purpose. Move it out to DEFAULT.
=> Move coordination_url option out of the storage section

gnocchi/gnocchi-config-generator.conf
The oslo.db template included by `gnocchi-config-generator` contains many
variable and confused people configure Gnocchi for the first time, especially
because the [database]connection field is there and not used.
Do not expose those values in the template to keep things simple.
=> Remove oslo.db from config generator

doc/source/rest.j2
People should leverage archive policy system and using
resample at last chance.
This change adds some notes about that.
=> doc: add some note about resample

doc/source/rest.j2, doc/source/rest.yaml
We should list all REST API use-case that people is asking for, to
not get issue opened for new feature when it's already possible to get
the data.
It's not always clear what API call I need to do to get all informations
I need for a use-cases.
This change starts a new section and add one example.
Related #465.
=> doc: introduces a REST use-cases section

gnocchi/tests/base.py
This module has been deprecated in favor of fixtures.MockPatch.
Change-Id: I52569c71989cbcb9ab34b7106e5d2a68abe204fb
(cherry picked from commit 35fe3b093ec97a83e41ca425b5d133202e60921b)
=> Using fixtures.MockPatch instead of mockpatch.Patch

gnocchi/cli/api.py
Some distro build uwsgi with dynamic plugins.
This change makes our cli working with and without uwsgi dynamic
plugins.
Closes #478
=> cli: load uwsgi plugins if needed

gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/test_aggregates.py, releasenotes/notes/aggregates-api-output-change-2bc6620c7f595925.yaml
aggregates: rework API output
This design have some issue when two timeseries have the same names,
only the last one is dumped. Or if the same metric is asked
twice for whatever reason, measures have all timestamps duplicated.
This change the result to a new format:
For resources:
{
"measures": { resource_id: {metric_name: {aggregation: MEASURES}}},
"references": [RESOURCES_DETAILS]
}
For metrics
{
"measures": {metric_id: {aggregation: MEASURES}},
"references": [METRICS_DETAILS]
}
When the result is aggregtated we got:
For resources:
{
"measures": { "aggregated": MEASURES},
"references": [RESOURCES_DETAILS]
}
For metrics
{
"measures": { "aggregated": MEASURES},
"references": [METRICS_DETAILS]
}
Closes-bug: #477
=> aggregates: rework API output

gnocchi/service.py
oslo.log sets the default root level for logging to INFO (or DEBUG in debug
mode). This means swiftclient inherits of the log level INFO and logs out ton
of requests info with their curl command in Gnocchi's log files.
This makes sure oslo.log configures swiftclient to be in WARNING mode anyway so
only the important information are logged.
This bug is not present with daiquiri (Gnocchi >= 4.0) since Gnocchi leaves the
global logging level to WARNING (Python default) to avoid such issues and only
configure Gnocchi's own root level.
=> Set default logging level for swiftclient to WARNING

gnocchi/common/redis.py
There's is a python-redis on PyPI, and that's not what we want.
Let's not be confusing.
(cherry picked from commit c89ebb5fb4b06297f8374df86b3e75d51afec494)
=> redis: enhance error message is redis is not installed

doc/source/install.rst, setup.cfg, tox.ini
Now that the `ceph` flavor is gone, let's use `ceph` for the recommended
approach and `ceph_alternative` for the other one.
=> Simplify Ceph flavor

doc/source/grafana.rst
The allowed_origin example is invalid.
This change fixes it and add some note about it, because even
oslo.config generates a comprehensive documentation about how to set
it, people prefer copying this bad example instead of reading the doc...
=> docs: add some note about grafana config

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/search.yaml
id key and like operator have some issue, due to the binary nature of
uuid.
This change avoids it.
Closes #450
Closes #491
=> rest: fix some id search issue

doc/source/intro.rst
There are at level 1 where they should be level 2
=> doc: fix heading level for titles in intro

gnocchi/cli/metricd.py
Ensure that a bytes type id is passed into tooz otherwise
metricd will fail to join the coordination group due to
an error concatenating the GROUP_ID with a str in tooz
when used with the memcached driver.
=> py3: pass a bytes type object to tooz coordinator

gnocchi/rest/api.py, gnocchi/tests/test_rest.py
The details on metrics need to be retrieved so the ACL can be correctly
applied.
Fixes #464
=> rest: load details on metric to apply ACL correctly

gnocchi/rest/api.py, gnocchi/rest/auth_helper.py, gnocchi/rest/policy.json, gnocchi/tests/functional/gabbits/metric-list.yaml
Use the auth_helper plugin mechanism to filter metric listing rather than an
hardcoded rule.
The Keystone rule is identical than before and filters based on
created_by_project_id fake-attribute.
The basic/remoteuser rule is changed to mimic the one for resources, i.e., no
filtering is enforced.
=> api: add a metric policy filter mechanism

doc/source/index.rst, doc/source/influxdb.rst, gnocchi/cli/api.py, gnocchi/incoming/__init__.py, gnocchi/indexer/__init__.py, gnocchi/opts.py, gnocchi/rest/api.py, gnocchi/rest/influxdb.py, gnocchi/tests/functional/gabbits/influxdb.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/test_influxdb.py, releasenotes/notes/influxdb-endpoint-13cbd82cf287d91c.yaml, requirements.txt
api: add an InfluxDB API endpoint
api: rename refresh_timeout option to operation_timeout
cli: use --http-socket rather than --http for uwsgi
=> Pull request for influxdb

gnocchi/indexer/__init__.py, gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
We currently returns all references, but when many of them point to the
same resource, we output each time the resource.
This change removes this resource duplication from the output.
=> aggregates: return resources/metrics only once

requirements.txt
New futures release breaks entirely on Python 3:
futures requires Python '>=2.6, <3' but the running Python is 3.5.2
Anyway it's a good idea to not install on Python 3.
=> Only install futures on Python 2

gnocchi/rest/api.py
I've noticed that "/v1/batch/resources/metrics/measures" endpoint executes database queries many times. Since ceilometer-agent-notification daemons often post batch data for many resources which have a same metric name, it is a bottleneck.
=> rest: reduce number of index queries

gnocchi/rest/influxdb.py
ResourceAlreadyExists exception is actually caught and retried upon by
get_or_create_resource_and_metrics(): it'll never be caught here.
get_or_create_resource_and_metrics() will abort with a 409 if that happens.
=> rest/influxdb: remove already caught exception

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/indexer/sqlalchemy/test_utils.py
oslo.config doesn't support %{} or %() variable interpolation while
ConfigParser does.
So when a password contains a '%', it's fine for oslo.config
But the Python ConfigParser will raise the exception.
Since alembic use ConfigParser and not oslo.config, we have to escape
the url ourself.
This is not a big deal since, we don't want alembic doing variable
interpolation.
=> indexer: fix upgrade when password contains a %

gnocchi/gendoc.py, gnocchi/rest/api.py, gnocchi/rest/app.py, gnocchi/tests/functional/gabbits/batch-measures.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/functional/gabbits/resource.yaml
Batch endpoint tell pecan body is a json, but we don't return body.
So pecan generates the body "null"
This change fixes that.
It also adds tests to ensure the all 202 don't have body set.
Closes #463
=> rest: don't return body on 202

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/influxdb.yaml
The current code convert an nonexistent variable into a string. Facepalm.
Let's return the correct exception into the correct format, and test it for
real using InfluxDB. The same will apply to Prometheus anyway.
=> rest: fix error handling on resource conflict

doc/source/operating.rst, gnocchi/cli/metricd.py, gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/opts.py, releasenotes/notes/metricd-respect-processing-delay-option-b8cc9895dec75567.yaml
This allows to disable eager processing of new measures.
Fixes #507
=> metricd: expose respect_processing_delay option

gnocchi/rest/api.py
This change have no tests, since the issue occurs only when the metric
is created by 2 HTTP calls in parallel.
Closes #552
(cherry picked from commit 7727d9aa65e2fdbc2dc6e228d64ab535a47a6a2e)
=> rest: fix exception handling in batch measures

setup.cfg
Last keystonemiddleware have some missing dependencies.
https://review.openstack.org/526624
Ban this version for now
(cherry picked from commit 989bf8db891a3fe7ab768f2d04a34ccb772c184c)
=> Ban keystonemiddleware 4.19

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/metric.yaml
The current code will fail with a 500 error.
(cherry picked from commit 63ea0aaa3a6b1c277f132afad157af5547b78b8b)
=> rest: fail properly if granularity is not a timespan

gnocchi/rest/api.py
This validate pagination options with voluptuous and remove the side effect of
modifying the query parametres. That avoids doing a copy of the dict each time.
=> rest: validate pagination options with voluptuous

doc/source/install.rst, gnocchi/rest/api.py
The current code in metric listing tries to validate the paging keys with
voluptuous, but they are actually and correctly validated later by
get_pagination_options(). Let's stop trying to be smart here and ignore them.
=> rest: do not validate paging keys in metric listing

tox.ini
py27-gate is not used anymore and I don't think anyone uses py27-gabbi, you can
just filter the test by name easily.
=> Remove unused tox targets

gnocchi/gendoc.py, tox.ini
There's no reason to stick with Python 2 for this job.
=> doc: build documentation with Python 3

gnocchi/rest/api.py
The only user-related problem that can be raised here is InvalidPagination. Any
other indexer exception would be a programming error, and should raise a 500
(and should be fixed). Do not convert blindly all IndexerException as it was
the user fault.
=> rest: do not catch too wide exception

gnocchi/storage/file.py
This has some cost which seems unneeded anymore. When this file is used, the
metric is locked by its sack, so there is no concurrent access to this file. We
can just write it at once.
=> file: do not write the unaggregated time serie atomically

gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/rest/api.py, gnocchi/rest/influxdb.py, gnocchi/statsd.py, gnocchi/storage/__init__.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_incoming.py, gnocchi/tests/test_storage.py
The current code passes Metric objects to the incoming subsystem, but it
actually knows only about metric ids. That's why it only uses metric.id
everywhere.
Let's simplify that and make the incoming subsystem completely agnostic with
the representation model of the metric outside of it.
=> incoming: only know about metric id

gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric-granularity.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/functional/gabbits/search-metric.yaml, gnocchi/tests/test_storage.py
storage: merge GranularityDoesNotExist and AggregationDoesNotExist
storage: remove double check of granularity
=> Pull request for no-ap-in-storage

gnocchi/rest/api.py, gnocchi/utils.py
- no real point creating a new list with tolist. zip can loop through
array
- to_timestamps requires a list so no point passing creating input
as generator
- numpy suggest to set 'count' when using fromiter. timeit shows
no real diff on small sizes
=> cleanup numpy+list usage

gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/test_storage.py
The storage API is currently responsible to check that requesting an
aggregation method for a metric is possible or not based on its archive policy.
This is out of its job actually, and it should just return an empty series if
it has nothing – or raise MetricDoesNotExist if the metric is unknown.
The API will take the job of doing this validation before hitting the storage
subsystem.
=> storage: stop checking for archive policy aggregation methods match

gnocchi/storage/__init__.py, gnocchi/tests/test_storage.py
The current code is pretty naive, and if you have S sacks and M metrics, it
will lock M sacks.
This patches groups metrics by sacks and lock S at max sacks only.
=> metricd: group metric by sack when expunging

devstack/plugin.sh
it's missing the storage section so incorrectly setting
coordination_url as the section
=> fix devstack coordination setup

devstack/plugin.sh
this patch adds a default config and uses template of version of
unitfile to restart redis
=> devstack: redis on opensuse needs to have default config

gnocchi/carbonara.py
- sort values and set the appropriate index which effectively
makes each index take the last value (min/max depending on sort order)
- in theory, allows us to cache order so we can reuse computation if
both min and max aggregates defined.
- this is ~1.3x better
=> speed up min/max aggregates

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/indexer/sqlalchemy_base.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search.yaml
To reduce the response size of search/list queries for gnocchi's grafana-datasource, I've added an `attrs` parameter.
```
GET /v1/resource/generic?attrs=id,type,user_id HTTP/1.1
POST /v1/search/resource/generic?attrs=id,type,user_id HTTP/1.1
```
Fixes #545
=> rest: narrow down the response attributes

gnocchi/cli/metricd.py, gnocchi/incoming/__init__.py, gnocchi/indexer/__init__.py, gnocchi/storage/__init__.py, gnocchi/utils.py
This retries and logs all failure to connect to any of the driver (index,
storage, incoming and coordinator). The wait time is not changed (exponential
up to 1 minute), but now both the API and metricd uses it this mechanism.
The error is also logged, so that any failure that is not connection related
(e.g. Python module missing) is properly logged and the operator knows what he
going wrong:
2017-12-15 10:37:49,075 [9070] ERROR    gnocchi.utils: Unable to initialize coordination driver
Traceback (most recent call last):
File "/Users/jd/Source/tenacity/tenacity/__init__.py", line 298, in call
result = fn(*args, **kwargs)
File "./gnocchi/cli/metricd.py", line 44, in get_coordinator_and_start
coord.start(start_heart=True)
File "/Users/jd/Source/tooz/tooz/coordination.py", line 423, in start …
=> Retry and log on drivers initialization failure

gnocchi/carbonara.py
- find the position of max value of each range
- calculate distance to middle based on range counts
- get floor/ceiling of middle (same if odd count), add, and divide.
- ~1.9x faster in random case
=> speed up median aggregate

doc/source/rest.j2
This change moves the list of API calls of Dynamic Aggregate before the
long list of available operations.
=> doc: reorder Dynamic Aggregate chapters

doc/source/operating.rst, gnocchi/carbonara.py, gnocchi/storage/__init__.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_storage.py, releasenotes/notes/carbonara-truncate-timespan-3694b96449709083.yaml, run-upgrade-tests.sh
The current truncation code in AggregatedTimeSerie truncate on object
initialize only. That means that split up to POINTS_PER_SPLIT points are
stored, and that data is read and _truncated_ at this point.
When new points are added (existing merge), it's possible that the number of
points grows more than the number of points defined by the archive policy,
storing too many points. That's hidden because when re-read, the
AggregatedTimeSerie is truncated again.
However, that makes the storage driver store too much data.
This patches remove the max_size attribute from carbonara.AggregatedTimeSerie
and simply expose a truncate() method that can be used to truncate each split
based on the oldest point that is defined by the archive policy.
=> storage: truncate aggregated time series before storing

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
only used in tests. this hasn't been used since v1.
=> remove unused from_tuples

gnocchi/carbonara.py
we don't need to construct an extra array to store intermediate
result. just zero'd ndarray we already built. this improves
serialization by ~2x
=> simplify uncompressed serialization path

gnocchi/indexer/sqlalchemy_extension.py, gnocchi/tests/functional/gabbits/resource-type.yaml
This changes adds all missing tests for PATCH an optional attributes of
a resource type (Only string type was having tests).
And fix the bug where False is returned instead of None for uuid.
Closes-bug: #616
=> tests: Fix resource type with optional uuid

gnocchi/service.py, gnocchi/tests/test_utils.py
Naming variable is hard
Fixes #605
=> service: fix utils.parallel_map number of workers setting

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
i mucked up #602 and the tests didn't find it. basically, the ordered
array i thought i build was not ordered by group as required to
make the logic of finding max and finding diff to middle, it was just
ordered with no regard to group.
this fixes it and expands the test so it's a bit more coverage.
this unfortunately is slower than what we merged. this is ~1.3x faster
unlike what i claimed before as ~1.9x faster
=> fix median aggregation

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py, requirements.txt, tox.ini
i believe i figured out how percentile is computed. this does
something very similar to median (for obvious reasons). at highlevel:
- get the index the percentile would land on and assume it falls
between indices
- take the values of the indices it falls between and figure out
weight of each value.
- handle the percentiles that fall on an exact index.
this is ~30x better. it's actually a bit slower (3%-5%?) than the
median computation so it's debatable if we want to remove median code.
drop scipy. also remove numpy.lib.recfunctions as it doesn't seem to
used anywhere.
=> optimise percentile computation with pure numpy

gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_rest.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py
storage: force granularities to be specified
rest/aggregates: declare _get_measures_by_name as static
test_rest: enhance error checking in negative aggregation test
=> Pull request for get-measures-wants-granularities

gnocchi/carbonara.py
- math says (a - 1) - (b - 1) = (a - 1) - b + 1 = a - b
- do the same thing for first aggregate rather than flipping array
- remove cast to datetime64[ns] when unserialising. this is already
enforced by the timeseries structure.
all these changes have neglible improvements in performance but i
think it's simpler to do less stuff.
=> cleanup some numpy math and casting

.travis.yml, gnocchi/service.py, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/test_utils.py
doc: do not test gnocchi.xyz build on stable branch
service: fix utils.parallel_map number of workers setting
tests: remove useless response_headers field that breaks with Gabbi 1.39.0
=> Pull request for stable-4.1-no-doc

gnocchi/indexer/__init__.py, gnocchi/indexer/sqlalchemy.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/archive-rule.yaml
This changes catch oslo.db error when archive policy
doesn't exists for an archive policy rule, and raise
ArchivePolicyNotFound instead.
Closes #627
=> indexer: ap rule, catch invalid ap

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/test_indexer.py
Fixes #530
(cherry picked from commit c89a0ef696a8bee5a95a336c599104c979c01b5f)
=> indexer: do not return empty IN statement in QueryFilter

gnocchi/tests/gabbi/gabbits/resource.yaml
(cherry picked from commit 05b000babec14e9afdafd105f21b39b628e39f6f)
=> tests: remove useless response_headers field that breaks with Gabbi 1.39.0

gnocchi/cli/metricd.py, gnocchi/rest/api.py, gnocchi/rest/app.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/functional/gabbits/base.yaml, gnocchi/tests/test_rest.py
metricd: use human readable member id
rest: export the available metricd processors in status
rest: store coordinator in pecan.request
=> Pull request for expose-workers-api

requirements.txt
NotIn was added in 0.8.10:
https://github.com/alecthomas/voluptuous/commit/f2241ce5edf6e16b3f3456f08f9b5bd7afe64a8d
=> bump voluptuous requirement

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
neither total_ordering nor python2 sets a default __ne__ value
behaviuor opposite to __eq__. this only happens in python3[1] so we
need to set this.
[1] https://docs.python.org/3/whatsnew/3.0.html#operators-and-special-methods
Fixes: #658
=>  set __ne__ method

gnocchi/tests/functional/gabbits/resource-type.yaml
this was originally incorrectly backported in d2ed3846b7e99b59de96827afc71a27b031225c6.
it fails as expected now. why? i don't know.
=> remove optional datetime resourcetype patch

gnocchi/tests/functional/gabbits/archive-rule.yaml, gnocchi/tests/functional/gabbits/resource-type.yaml
- 8303ce4254c213de2dbb6bb1d0b86050e4c3e665 incorrectly backported
datetime attribute which didn't exists.
- e3176cb77d0c2377a0504db065f9a75024493ccd incorrectly backported
bad test as it's matching a string that requires jsonify from
9545e50631c5b8f30635d958fcfff29ee711e245
no idea why either one passed checks originally.
=> fix bad backports

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
neither total_ordering nor python2 sets a default __ne__ value
behaviuor opposite to __eq__. this only happens in python3[1] so we
need to set this.
[1] https://docs.python.org/3/whatsnew/3.0.html#operators-and-special-methods
Fixes: #658
(cherry picked from commit 70cc23c4289b97c8fb3e0f12d5dadc00549516f3)
=> set __ne__ method

gnocchi/tests/functional/gabbits/resource.yaml
all the xfail tests associated with original commit
a952877a34a5027db0d1111dbfcca67ad47dc8ed have been fixed/removed.
clear note to avoid noise.
=> remove old leftover note

gnocchi/cli.py
This change stop the coordinator before existing on membership issue.
=> metricd: stop coordinator on membership issue

gnocchi/cli.py
The patch in f5f2e3e9e8d0c36e23a5ad21ec3dc425cdc214cc was way too optimistic:
@utils.retry only retries if `utils.Retry` is raised. Here, a random exception
can be raised and then it crashes back to Cotyledon which restarts without
delay.
This patch transforms any `Exception` to `utils.Retry` so retrying is used and
wait before retrying, rather than having cotyledon restarting right away.
Closes: #681
=> metricd: fix retry being too aggressive

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/functional/gabbits/search.yaml
The not operator was buggy. This change fix it.
Closes: #649
(cherry picked from commit 246dd263e91e240cdbf74d253e09f834233ef21d)
=> indexer: fix not operator

doc/source/statsd.rst
this commit fixes some minor grammatic issues with
the statsd daemon documentation.
=> docs: grammar fixes for statsd.rst

doc/source/rest.yaml, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/batch-measures.yaml, gnocchi/tests/functional/gabbits/metric.yaml, releasenotes/notes/ap-in-batch-d83f6aa163d200e9.yaml
This change allow to pass the archive policy when we batch
measures for metrics.
=> batch: allow to pass archive policy

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/test_indexer.py
This allows to re associate another metric using the same name as used
previously, even if the metric is not expunged yet.
Closes: #702
=> indexer: detach metric from resource when marked as 'deleted'

gnocchi/incoming/redis.py, gnocchi/storage/__init__.py
This is actually faster than concatenating numpy arrays.
=> redis: concatenate bytes before unserializing

doc/source/rest.j2
- Change documentation of user and project attributes based on comments
in #698.
- Link to timestamp format description when mentioning timestamps.
- Minor rephrasing in the paragraph regaring the id attribute
Please feel free to request changes before merging! :)
=> further work to make resource create docs match reality

gnocchi/carbonara.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/s3.py, gnocchi/rest/aggregates/operations.py
it just does some validation we don't need then calls concatenate[1].
just call concatenate so we use it consistently everywhere.
[1] https://github.com/numpy/numpy/blob/99019107cbde06294a356fd7fc859f9b31f87410/numpy/lib/function_base.py#L4326
=> use concatenate consistently

gnocchi/storage/redis.py
The current code starts by doing this, but actually the HSCAN call is a good
hint as whether the metric exist or not.
=> redis: only check key existence if no keys are retrieved

gnocchi/storage/__init__.py, gnocchi/storage/redis.py
If no keys have to be retrieved, we can skip the backend code and just
return an empty list.
This is specially needed by redis that need at least one key for
using hmget.
=> redis: hmget requires at least one args

gnocchi/cli/api.py
--thunder-lock is recommended when we mix threads and processes.
http://uwsgi-docs.readthedocs.io/en/latest/articles/SerializingAccept.html
"--hook-master-start", "unix_signal:15 gracefully_kill_them_all make
child receving sigterm instead of sigkill on exit. This should avoid having
some connections still in TIME-WAIT after the process stop.
=> api: add some uwsgi flags

.travis.yml
We don't need to test this on stable branches.
=> travis: remove docs-gnocchi.xyz from stable/4.2 branch

gnocchi/archive_policy.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py
This frees a bit more the storage engine from the archive policy system.
=> storage: pass Aggregation object to storage get_measures()

.travis.yml, tox.ini
We current install Gnocchi twice, once with no extra and develop mode,
and a second time with extra but without develop mode.
This change install gnocchi only once with extra and develop mode.
=> tox: don't install gnocchi twice

gnocchi/cli/manage.py, gnocchi/cli/metricd.py, gnocchi/rest/api.py, gnocchi/rest/app.py, gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_storage.py
The storage engine does not need a coordinator, except for locking sacks.
However sacks do not belong to the storage driver itself, so it makes no sense
to requires one.
=> storage: stop requiring a coordinator

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric.yaml
The current validation code validates measure aggregates retrieval against the
whole list of valid aggregation methods. That serves little purpose as it is
again validated just after against the actual list of existing aggregation
method defined in the archive policy attached to this/these metric(s).
This patch removes that validation and adds a missing test for the aggregation
endpoint.
=> api: simplify archive policy validation

doc/source/operating.rst
The documentation suggested that the number of sacks could be tuned
via a configuration option the in gnocchi.conf file.  This commit
corrects the docs to indicate that the value can be changed only with
the gnocchi-change-sack-size command.
This commit also corrects spelling, grammar, and formatting issues in
the same section.
=> improve documentation on tuning the number of sacks

gnocchi/storage/__init__.py
Those values are already computed earlier, no need to do it again here.
=> storage: remove useless recomputing of values

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/rest/api.py, gnocchi/rest/app.py, gnocchi/storage/__init__.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_rest.py, gnocchi/tests/test_statsd.py
This moves those methods out of storage and where they belong: in the Chef!
=> chef: import process_new_measures and refresh_metric

gnocchi/archive_policy.py, gnocchi/rest/__init__.py
voluptuous does not know how to use set and now wants to check that the default
value validates against the validators.
=> rest: stop using set to validate archive policies

gnocchi/rest/api.py
voluptuous expects a list, the list-like oslo.config doesn't work well
on py27. So this change casts it a real list.
=> Use list as default aggregation_methods

devstack/gate/post_test_hook.sh, gnocchi/tempest/scenario/__init__.py, gnocchi/tests/gabbi/gabbits-live/live.yaml, gnocchi/tests/gabbi/gabbits-live/search-resource.yaml
Some tempest tests fail because their hardcode list order, while
Gnocchi can return an order order.
To fix them, this is a partial cherry-pick of
aa0716be945352e2d9ac65a8861916b9e634d1f0
Change-Id: I7d609a778c7c8592a3c7847e62b832d3805a71f4
=> tests: fix tempest tests.

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py, gnocchi/tests/test_utils.py, gnocchi/utils.py
This replaces this method in each storage driver by a new one that can retrieve
several unaggregated timeseries at the same time. The storage engine does not
leverage it and only passes a list of one metric… for now.
=> storage: replace _get_unaggregated_timeserie by _get_or_create_unaggregated_timeseries

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
This allows to store several unaggregated timeseries at the same time.
=> storage: replace _store_unaggregated_timeserie by _store_unaggregated_timeseries

gnocchi/storage/__init__.py, gnocchi/tests/test_storage.py
This implements a batched version of the split storage for a metric so that
both the fetching of existing and storing of new splits are batched.
=> storage: replace _store_timeserie_split by _store_timeserie_splits

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
This new method allows to delete a bunch of splits at the same time for a
single metric, batching delete.
=> storage: change _delete_metric_measures to _delete_metric_splits

gnocchi/carbonara.py, gnocchi/storage/__init__.py
This moves the handling into Carbonara itself so the storage engine does not
have to handle that.
=> carbonara: handle timeseries derivation for rate aggregations

gnocchi/carbonara.py, gnocchi/storage/__init__.py, gnocchi/tests/test_carbonara.py
The current return format is very specific to the Gnocchi API, whereas there
should not be any need to do the formatting at this low-level stage.
=> carbonara: make fetch() return an AggregatedTimeSerie

gnocchi/carbonara.py, gnocchi/tests/test_carbonara.py
While you can't sort and compare SplitKey with different sampling, you can say
if they are equals or not easily.
=> carbonara: allow eq and ne comparison to SplitKey

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/gendoc.py
All resource search payload can also be passed in the filter parameter
into other format. This is missing from the documentation while Grafana
have to use this format. So documents it
=> doc: document filter parameter

gnocchi/carbonara.py, gnocchi/storage/__init__.py
There's no reason to truncate each split if we truncate the AggregatedTimeSerie
once and for all before splitting it.
=> storage: truncate the whole AggregatedTimeSerie, not every split

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/resource-aggregation.yaml, releasenotes/notes/filter-param-for-aggregation-f68c47c59ca81dc0.yaml
The filter= argument is missing from the aggregation API.
This change adds it.
=> Add filter format in aggregation

setup.py, tox.ini
We use environment marker in requirement so we need at least
setuptools 20.6.8.
This must be a setup_requires because pbr use setuptools to read the
requirement.
=> Set minimal setuptools version

tox.ini
By default tox built a sdist with the python OS packages. We already
skip install/develop phase and manually use "pip install -e"
The sdist is useless and removing it allow to run tox on old OS
that doesn't have a recent setuptools.
=> doc: don't build sdist

gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/storage/s3.py, gnocchi/tests/test_storage.py
This decision is now available for the upper layer.
=> storage: do not return empty data set on non-existing metric

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
The list of keys passed as argument now embeds also its companion Aggregation
object so it'll be possible to retrieve splits from different aggregations in
one single call.
=> storage: allow to pass different aggregations to measures retrieval functions

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py
Raising an exception at this point is damageable as when multiple SplitKeys are
being fetched at the same time, only one being absent will cancel the call. The
caller is already solid and know show to handle None as a return value so just
use None to indicate the split is non-existing.
=> storage: stop raising AggregationDoesNotExist on measures retrieval

gnocchi/storage/__init__.py, gnocchi/tests/test_storage.py
If data corruption occurs, the _get_splits_and_unserialize() method might not
return the same number of arguments that it received. It's not a big deal when
concatenating the splits to retrieve the data for reading. However, when
requesting a bunch of splits for rewrite, that's a problem because the list is
zipped with other data on iteration, possibly corrupting the results.
=> storage: fix corruption scenario

gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
Splits are either retrieve for reading from:
- the REST API, where the splits are actually listed before being retrieved, we
don't care about the metric existence or not, None is enough.
- on rewriting the split (WRITE_FULL) and in that case we know the metric
exists
=> storage: remove metric existence check when retrieving splits

gnocchi/storage/ceph.py
`object_names` is an iterator that is iterated twice, therefore it's empty the
second time and no objects are removed. This patches fixes that.
Source: https://bugzilla.redhat.com/show_bug.cgi?id=1549922
=> ceph: fix unprocessed measures deletion

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
This allows to batch storage and deletion of splits for a metric.
=> storage: _add_measures can handle multiple aggregations at the same time

gnocchi/common/redis.py
Whilst working on the Reproducible Builds effort [0], we noticed
that gnocchi could not be built reproducibly as it iterates over
a Python set when generating documentation.
This was originally filed in Debian as #892419.
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892419
Signed-off-by: Chris Lamb <lamby@debian.org>
=> Make the build reproducible

gnocchi/storage/__init__.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_carbonara.py
Rather than emitting store and delete on each aggregation computing, this
batches them all at once for a metric by returning the operations from
`_add_measures` directly.
=> storage: more batching of store/delete operations in add_measures

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/common/redis.py, gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/tests/base.py, gnocchi/tests/test_chef.py
This adds a new method process_measures_for_sack to incoming storage driver. It
allows to read an entire sack for new measure rather than individual metrics.
This avoids doing 2 listing to process new metrics and only does one to load
the measures.
The process_new_measures(metrics) is kept for the refresh_metric() use case for
now. Some refactoring might be possible after this patch.
The S3 storage driver is a bit modified to store the incoming measures in
<sack>/<metric>/ rather than <sack><metric>/ so it's easier to list incoming
sacks and metrics.
=> incoming: introduce process_measures_for_sack

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/rest/api.py
This makes it safer to call it without taking care of the lock externally.
=> chef: lock sack when using process_new_measures_for_sack

gnocchi/chef.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
This allows in this first step to retrieve and store the unaggregated
timeseries all at once.
=> chef/storage: process all metrics from the sack in one single batch

setup.py
SOURCES.txt generated by this version is wrong and broke bdist*
commands.
This change ignores this version.
Next setuptools_scm version should fix it:
https://github.com/pypa/setuptools_scm/pull/227
https://github.com/pypa/setuptools_scm/pull/233
https://github.com/pypa/setuptools_scm/pull/234
=> git: ignore setuptools_scm 1.16.0/1/2

gnocchi/tests/functional/gabbits/resource-aggregation.yaml
Some of the tests in another scenario use those id already, making a potential
conflict.
=> tests: fix duplicate resource id between tests

gnocchi/chef.py, gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/rest/api.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_rest.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py, gnocchi/tests/utils.py
This simplifies the code base by just allowing to process new measures sack per
sack with the existing process_new_measures_for_sack() or to use the new
refresh_metrics() who takes a list of metrics. Since the list of metric must be
known, there's no need to use list_metric_with_measures_to_process() anymore,
so it can be removed.
=> chef: merge refresh_metric and process_new_measures

gnocchi/storage/__init__.py
truncating might zero out the entire split. don't serialize and store
empty series.
Fixes: #848
=> check if split is empty

gnocchi/tests/test_statsd.py
The current tests can fail just because the timeout it not set to None. The
base method trigger_processing is meant to be used just for that!
=> tests: replace refresh_metrics() with trigger_processing in statsd

gnocchi/carbonara.py
i have no idea why but:
```python
In [1]: import numpy
In [2]: dates = numpy.array([numpy.datetime64('2018-01-01') +
numpy.timedelta64(1, 'D') * i for i in range(1000)])
In [3]: values = numpy.random.rand(1000)
In [4]: arr = numpy.empty(len(values), dtype=[('dates', '<datetime64[D]'),
('values', '<d')])
In [5]: arr['dates'] = dates
In [6]: arr['values'] = values
In [7]: timeit blah = [tuple(i) for i in arr]
1.52 ms ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [8]: timeit blah = [i for i in zip(arr['dates'], arr['values'])]
112 µs ± 2.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [9]: timeit blah = arr.tolist()
139 µs ± 1.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [10]: timeit blah = [i for i in arr]
57 µs ± 3.49 µs per loop …
```
=> speed up iteration over ts

gnocchi/service.py, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_archive_policy.py
Even with tests debug disable, each test prints the configuration
options. And when enable some logs are missing.
This change changes the approach. Now by default, we sent log to a
fakelogger. And we print the stdout/stderr/logs when it fails or when
tests debugging is enabled.
=> tests: Fix debug logging

gnocchi/cli/injector.py, gnocchi/tests/test_injector.py, releasenotes/notes/injector-af9e68fdfe02d322.yaml, setup.cfg
This allows to inject measures and maybe process them in a single tool. This is
useful to generate load to test metricd and also profile the processing code.
=> Add gnocchi-injector

gnocchi/common/swift.py
We miss to pass the project domain to swiftclient.
This change does it.
=> swift: pass the project domain

gnocchi/indexer/alembic/versions/397987e38570_no_more_slash_and_reencode.py, run-upgrade-tests.sh
The current script cannot be executed if a resource has an history entry:
ERROR gnocchi oslo_db.exception.DBReferenceError: (psycopg2.IntegrityError) update or delete on table "resource" violates foreign key constraint "fk_rh_id_resource_id" on table "resource_history"
DEBUG [pifpaf.drivers] gnocchi-upgrade[71041] output: 2018-04-24 09:36:08.029 71041 ERROR gnocchi DETAIL:  Key (id)=(e8bce9ff-5c30-524c-87b8-bfb1dce7855b) is still referenced from table "resource_history".
DEBUG [pifpaf.drivers] gnocchi-upgrade[71041] output: 2018-04-24 09:36:08.029 71041 ERROR gnocchi  [SQL: 'UPDATE resource SET id=%(param_1)s, original_resource_id=%(original_resource_id)s WHERE resource.id = %(id_1)s'] [parameters: {'param_1': 'bd6eac67-c1e9-5da0-9979-a797d776039e', 'original_resource_id': …
=> indexer: drop/create missing constraint in slash reencoding migration script

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
It also fixes the parallel_map call to be unique, making _get_splits a little
bit faster for unbatched drivers.
=> storage: allow to batch splits retrieval for multiple metrics

gnocchi/incoming/__init__.py, gnocchi/incoming/swift.py, gnocchi/storage/__init__.py, gnocchi/storage/swift.py, gnocchi/utils.py
This change removes usage of threads with swift driver.
This avoids to get "Connection aborted" because a thread is stuck
and the server side decide to break the connection.
Related-bug: #509
(cherry picked from commit bc18ebded10bc763b98bcba46db925a3a5031ecd)
=> swift: avoid Connection aborted

gnocchi/storage/file.py, gnocchi/tests/base.py
Doing so on each storage driver instance slows things down and can make thing
not working in case of (transient) failure for no good reason.
=> storage/file: create directories only on upgrade()

gnocchi/storage/file.py, gnocchi/tests/test_storage.py, releasenotes/notes/change-file-driver-layout-41c7a458160c4cb7.yaml
Some filesystem have a limit in term of number of directory a directory
can have. Also in performance point of view, some filesystem are slower
when too much directories are created in one directory.
To improve the situation is such case, this change adds an option
to create subdirectories for storing metrics.
for example file_subdir_len=2 will create:
de/de3a72c4-5055-43b4-bed1-f9bb1395c52a
=> file: allow to create a subdir to create less root directory

setup.cfg
redis-py has a python and c parser[1]. install the c parser. it offers
~10%-90% performance improvement depending on task using benchmark from
redis-py[2].
[1] https://github.com/andymccurdy/redis-py#parsers
[2] https://github.com/andymccurdy/redis-py/blob/master/benchmarks/basic_operations.py
=> redis: use hiredis parser

gnocchi/rest/api.py
If no resource_id or no metric names are passed in the batch payload,
we can skip some sql queries.
This change does that.
Closes-bug: #911
=> api: avoid some indexer queries

doc/source/client.rst
Add notes about open source Go SDK implementation for the Gnocchi API
with links and installation instruction.
For #926
=> Docs: add reference to a Go SDK

gnocchi/incoming/__init__.py
incoming data isn't that large (usually) but if we don't need to build a list
why build it.
=> use fromiter to build array

gnocchi/storage/redis.py, gnocchi/tests/test_storage.py
The iteration over the results was wrongly computed and did not return data for
the second metric and following.
=> redis: fix list_split_keys with multiple metrics

gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/test_amqp1d.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py, gnocchi/tests/test_utils.py
This stops using deprecated storage.get_measures and instead uses storage.get_aggregated_measures
=> Stop using deprecated storage.get_measures

.travis.yml, setup.cfg
This is needed by reno.
docs-gnocchi.xyz job does not work see #953
=> docs: use remove sphinx < 1.6 limitation, disable gnocchi.xyz doc job

gnocchi/storage/__init__.py, gnocchi/tests/test_storage.py
The high archive policy created by default contains three different
granularity definitions - 1 second, 1 hour and one day. For such
metrics the split computation has been done incorrectly as it was
using oldest keys not taking into account those keys granularity.
It caused TypeErrors when comparing two SplitKeys with different
granularities.
closes: gnocchixyz/gnocchi#959
=> Fix computation for metrics with multiple granularities

doc/source/rest.j2
the REST output seems to be clashing with the formatting of previous
element. remove the formatting and move the REST output above.
=> fix doc formatting

gnocchi/rest/aggregates/operations.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml
Old aggregate API was allowing rate:XXX format for rateofchange
aggregation.
This change restores it since we use the new internal API.
Closes: #1016
=> Allow rate:XXX aggregations

gnocchi/indexer/__init__.py, gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
it's possible that not all groups will contain a specific metric.
rather than fail, return the groups that do have the matching metric.
only if all groups don't have matching metrics, should we fail.
Fixes: #1013
=> don't fail everything if one group missing metric

gnocchi/gendoc.py
gendoc throws: `AttributeError: 'Sphinx' object has no attribute 'info'`
use logging provided by sphinx.util (not sure why it's using sphinx logger
but meh)
=> fix gendoc

.mergify.yml
With the low activity going on, it might be hard to get two reviews.
=> Reduce the number of required reviewers

gnocchi/rest/aggregates/processor.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
infinity and nan are not part of json standard. the default python
json serialiser will dump `inf` and `nan` (unquoted) and load the
them.
we've historically returned `nan` and supported ignoring it by specifying
`fill=dropna`.
i don't believe `"inf"` or `"nan"` is significantly better and since
i don't want to break existing behaviour of nan, i think it's best
to just treat infinity as we do nan for now. anything more opinionated
probably requires more discussion.
related: #1023
=> handle infinity like nan

gnocchi/storage/__init__.py
this was previously used to log the aggregation performance (points/time).
this logging doesn't exist anymore since we moved to bulk saving so
remove it.
=> remove unused statistic code

gnocchi/carbonara.py, gnocchi/rest/aggregates/processor.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml
- don't create a new array when getting unique times across series
- create a common sum function instead of making a sum timeseries and
ripping out just the values.
=> minor cleanup

.travis.yml
it's not installing correct version when it installs twine during
deploy
=> try forcing newer version of six on to travis image

.travis.yml
- force upgrade of six
- remove README.rst cleanup as it's been done permanently (and i didn't
realise this line existed when i did it)
- add skip_existing[1]. each ENV runs the deploy so travis tries to
upload multiple times and fails on each ENV except for the first
[1] https://docs.travis-ci.com/user/deployment/pypi/#upload-artifacts-only-once
=> fix travis deploy

.travis.yml, README.rst, doc/source/client.rst, gnocchi/gendoc.py, gnocchi/tests/functional_live/gabbits/search-resource.yaml, setup.cfg, tox.ini
This is the current hosting platform now that the name has expired.
=> Change URL to gnocchi.osci.io

gnocchi/rest/api.py, gnocchi/rest/exceptions.py, gnocchi/tests/functional/gabbits/resource.yaml
To help operators to debug some API errors, was added some logs in warning and debug level to log the responses in Gnocchi rest API.
=> Enhance rest api logging

gnocchi/indexer/alembic/versions/04eba72e4f90_rename_ck_started_before_ended.py, gnocchi/indexer/alembic/versions/40c6aae14c3f_ck_started_before_ended.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py
Under newer MySQL versions, check constraints must have unique names.
Drop and re-create the check constraints on the resource and
resource_history tables to ensure that they are uniquely named
for upgrades in existing deployments.
Ensure that check constraints are created with unique names in
new deployments.
=> Fix compatibility with MySQL >= 8

gnocchi/rest/api.py
In the StatusController the statistics for the
members on python3 is a byte string which cannot
be jsonified.
This changes so it loops through the statistics
for the member and ensures the key is a string
and not a byte string.
=> Ensure member statistics key is decoded

gnocchi/indexer/alembic/versions/5c4f93e5bb4_mysql_float_to_timestamp.py, gnocchi/indexer/alembic/versions/aba5a217ca9b_merge_created_in_creator.py
Closes: https://github.com/gnocchixyz/gnocchi/issues/1080
Related to: https://github.com/sqlalchemy/sqlalchemy/issues/5669
=> Fix migrations reusing column objects

gnocchi/rest/api.py, gnocchi/tests/test_rest.py, setup.cfg
We hardcode the content-type on all DELETE requests
otherwise Pecan will throw NotAcceptable errors when
doing requests to the APIs without any content-type set
and will default to text/html.
=> Set json template for DELETE requests

gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, run-func-tests.sh, run-upgrade-tests.sh
Use the Ceph CLI instead of Rados command
in the fixtures.
Also make sure we delete pools when we cleanup
after gabbi runs in stop_fixtures() that was
missing.
=> Use Ceph CLI

gnocchi/gendoc.py, setup.cfg, tox.ini
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,
as the default Loader is unsafe. Please read https://msg.pyyaml.org/load
for full details.
=> Fix yaml deprecation warning

gnocchi/cli/api.py, gnocchi/rest/policy.yaml, releasenotes/notes/migrate-policy-format-from-json-to-yaml-3287dfaeee6abfa2.yaml
In OpenStack projects we are deprecating usage of json for policy file
and will use yaml by default[1]. This change introduces the default
yaml file and replace the default of policy_file to follow that
migration because Gnocchi depends on the same oslo.policy library.
The old json file is kept because there are several distros like RDO
which uses the file, but it will be removed in a future release.
[1] https://governance.openstack.org/tc/goals/selected/wallaby/migrate-policy-format-from-json-to-yaml.html
=> Use yaml for policy file by default

gnocchi/gnocchi-policy-generator.conf, gnocchi/rest/app.py, gnocchi/rest/policies.py, gnocchi/rest/policy.json, gnocchi/rest/policy.yaml, releasenotes/notes/policy-in-code-2ded688177f2dc19.yaml, setup.cfg
This change implements default policies in code. With this change, operators no longer need to define the default policy rules in policy configuration file(policy.yaml) unless they need any customized rules.
=> Implement default policies in code

gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py
This change replaces the usage of policy.json by policy.yaml in test
codes, because Gnocchi service now uses policy.yaml by default.
=> Use policy.yaml in tests

.travis.yml
The tests were disabled in a previous commit, but the goal is to have more and more stable tests.
=> Re-enable tests using swift and s3 backend

setup.cfg
It broke e.g ceilometer/aodh on devstack.
This reverts commit a2d84f5b1b0555ad83b14e931d9bd7065f2f7b6a.
I acknowledge, this is controversial, see 
https://github.com/gnocchixyz/gnocchi/commit/a2d84f5b1b0555ad83b14e931d9bd7065f2f7b6a#comments
for discussion
Resolves: https://github.com/gnocchixyz/gnocchi/issues/1095
=> Revert "Pin oslo.policy<=3.4.0"

gnocchi/rest/policies.py
The parameter name prefixed with ROLE_ should be used for policy rules
with rule: syntax. This renames the parameters to define policy strings
accordingly.
=> Use ROLE_* for rule based policies

.mergify.yml
to prevent accidental merges of non-reviewed
changes.
Related: https://github.com/Mergifyio/mergify-engine/issues/1860
=> Dismiss reviews after pushing a new commit

setup.cfg
tenacity has a dropped backwards compatible changes for
version 7.0.0 and sqlalchemy in 1.4 causes an issue
with sqlalchemy_utils.
=> Pin sqlalchemy and tenacity

run-upgrade-tests.sh, tox.ini
Don't upgrade between released versions but use tags
or branches instead. When dependencies breaks it's
easier to get jobs passing without having to release
instantly.
=> Run upgrade testing from git

.travis.yml
We won't maintain CI for 4.2 so we won't
test upgrade.
=> Drop upgrade jobs from 4.2

gnocchi/amqp1d.py, gnocchi/indexer/alembic/versions/5c4f93e5bb4_mysql_float_to_timestamp.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/rest/auth_helper.py, setup.cfg, tox.ini
This PR fixes multiple issues.
=> Fix Python 3.8, SQLAlchemy 1.4 and MySQL 8

doc/source/releasenotes/3.0.rst, doc/source/releasenotes/3.1.rst, doc/source/releasenotes/4.0.rst, doc/source/releasenotes/4.1.rst, doc/source/releasenotes/4.2.rst
old stable branches was renamed to eol-<version>
so that needs to be updated.
=> doc: update reno branches to new eol names

.github/workflows/gnocchi.yml
Only run the actions on PR and not
on push because that runs the actions
when a PR is merged.
Dont hardcode the default branch to master
since it actions will use the same ref/commit
that it's going to test when loading workflows.
Removing the default branch makes it easier to
just backport later.
=> ci: dont run actions on push and dont hardcode default branch

setup.cfg
and thus we should bump the requirement.
=> Policy in code requires oslo.policy >= 3.5.0

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/opts.py, gnocchi/tests/test_chef.py, releasenotes/notes/configurable_clenaup_batch_size-a785c1aa6ee29058.yaml
Currently gnocchi-metricd tries to collect all metrics that should be deleted
and deletes them in one big loop. If a large amount of old metrics has
accumulated this will cause high load on the database as it needs to find
and sort all of these rows. It will also cause a high amount of memory usage
for gnocchi-metricd as it needs to also sort all of these rows in memory.
To fix this the amount of rows being deleted in one run is limited to 10000.
This is sufficient to allow gnocchi to cleanup metrics in a fast way under
normal circumstances while still allowing it to catch up if no deletion has
been performed for a while.
Signed-off-by: Felix Huettner <felix.huettner@mail.schwarz>
=> Limit maximum metrics to be deleted simultaniously

doc/source/index.rst
Using a specific string as the magic marker. Repeated as an actual string (on line 5) because '...-after' is actually after that line, not that line and later. Can't seem to use a comment/crossref marker like `.. _doc_include_marker:` and `start-after` that. If the intro README line changes, then the docs build will break, rather than strangely truncating.
If you want to just keep the `start-line` option, it's now 9.
=> Fix README include bound

setup.cfg
Python 3.6 is used in CI and tested.
(cherry picked from commit 0270c728574fd36e101db5e24b625a123784c9db)
=> Mark Python 3.6 as supported

gnocchi/common/redis.py, setup.cfg
which was introduced in redis_py >= 3.3. It helps with keeping
connections alive and to prevent  ServerConnection errors.
=> Use health_check_interval

gnocchi/cli/api.py, gnocchi/rest/policy.yaml, gnocchi/tests/base.py, gnocchi/tests/functional/fixtures.py, releasenotes/notes/migrate-policy-format-from-json-to-yaml-3287dfaeee6abfa2.yaml, setup.cfg
Since oslo.policy 3.4.0, support for policy.json has been deprecated in favor of the yaml format [1]
This PR is a backport of the required changes to migrate from policy.json to policy.yaml, so that each distro can consume a version with policy.yaml used by default.
[1] https://docs.openstack.org/releasenotes/oslo.policy/victoria.html#relnotes-3-4-0-stable-victoria
[2] https://governance.openstack.org/tc/goals/selected/wallaby/migrate-policy-format-from-json-to-yaml.html
=> Use policy.yaml by default

.mergify.yml, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml
This contains new CI fixes.
* pyparsing >= 3.0.0 changed behavior of ``__bool__`` on pyparsing.ParseResult class
* Update asserRegex for gabbi tests where pyparsing changed the output
* Update mergify config to remove the ``strict`` key in the ``merge`` dict
=> New CI fixes

doc/source/rest.j2
=> doc: Remove colon for multi metric-id aggregates

gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, releasenotes/notes/aggregates-no-metric-9be5a8894bad09ee.yaml
Return a 404 (metric not found) rather than 400 (bad request) when
metrics associated with a dynamic aggregate are not found.
=> dynamic aggregates - metric not found

setup.py
The latest release of setuptools 61.0 made a breaking change[1] and
because of this change 'pip install' fails with the following error.
~~
error: Multiple top-level packages discovered in a flat-layout:
['lib', 'spec', 'manifests', 'releasenotes'].
~~
Users that don't set 'packages', 'py_modules', or configuration'
are still likely to observe the auto-discovery behavior, which may
halt the build if the project contains multiple directories and/or
multiple Python files directly under the project root.
To disable auto discovery, one can do below in setup.py
~~
setuptools.setup(..,packages=[],..)
~~
or
~~
setuptools.setup(..,py_modules=[],..)
~~
[1] https://github.com/pypa/setuptools/issues/3197
=> setuptools: Disable auto discovery

gnocchi/utils.py, setup.cfg
This adds support for later version of the
tenacity library and unpins the dependency.
This depends on the tooz [1] change or it
will fail.
[1] https://review.opendev.org/c/openstack/tooz/+/829412
=> Support later versions of tenacity

gnocchi/utils.py, setup.cfg
Drop the monotonic library and use the
standard time library instead.
Fixes: #1232
=> Use monotonic from time standard library

setup.cfg
The newer release requires us to regenerate the
protos from the remote.proto file.
=> Pin protobuf<4.0.0

.github/workflows/gnocchi.yml, .mergify.yml, setup.cfg, tox.ini
This change adds Python 3.9 to supported python versions and adds
test coverage for it. CentOS Stream 9 now uses Python 3.9 by default
so the support is required to run Gnocchi in CentOS Stream 9.
This change also adds a few metadata items to setup.cfg to enforce
usage of Python >= 3.6.
=> Support Python 3.9

gnocchi/cli/api.py, setup.cfg
Commit 0d610f6dcdfa4cb95e6832aff5054da247052a10 was supposed to switch
default policy file from policy.json to policy.yaml but that change
was incomplete and still the old policy.json is searched first.
This change fixes it and ensures policy.yaml is loaded first.
=> Fix incomplete switch to policy.yaml

setup.cfg
This partially reverts 87ef6cd26e0bb0e60ce680057f4f4380d3da7e67 and
reverts the change of minimum version of oslo.policy. The change
depends on the interface available in older versions and that bump
was not really necessary.
=> Revert unnecessary bump of oslo.policy

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/indexer/sqlalchemy_base.py, gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, gnocchi/tests/test_measures_grouper.py
Problem description
===============
When we are aggregating measures using Gnocchi, we can group the measures by resource's metadata. However, Gnocchi does not group the measures taking into account the resource's metadata history; so if some resource's metadata changed recently, it will be grouped using only the last metadata value. 
Imagine the following situation:
I have a metric with metadata called "name", so I take a resource that is monitored by this metric and I change the resource's name from "test" to "test1" at 14:45:00. Then I call the Gnocchi's Aggregation API with an interval from 11 to 17 hours grouping by "name" and it returns this:
| group                  | name       | timestamp                    | granularity | value               | …
=> Group measures by resource metadata history

gnocchi/indexer/sqlalchemy.py, gnocchi/rest/api.py, gnocchi/utils.py
An issue was found when Ceilometer notification is stopped, and samples accumulate in the RabbitMQ. These samples might contain the same set of attributes that would trigger one revision. However, due to a concurrency issue, when Ceilometer notification is started back again, all of them are processed in almost the same moment, and then pushed back to Gnocchi API. Then, in Gnocchi API the detection to see if the resource needs a revision is executed outside of a semaphore control (e.g. read/write transaction with the DB with a table being locked). Therefore, the code detects that a revision is needed, and generated multiple revisions, which have the same content but different revision start and end.
This patches aims to resolve that situation. The solution adopted is to check again in the …
=> Concurrency issues when multiple patches happen for the same resources

setup.cfg
The copy kwarg on astype() was not introduced until 1.14.0 and we are using that in multiple places.
=> deps: set numpy>=1.14.0

tox.ini
While running the tests locally with the latest tox I was getting the following error message:
```
pep8: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'LANG GNOCCHI_TEST_* AWS_*'
pep8: FAIL code 1 (0.00 seconds)
evaluation failed :( (0.09 seconds)
```
That error is happening because of the passenv declaration. This patch is proposing a fix for that.
=> Fix `passenv` declaration in tox.ini

.gitignore, gnocchi/indexer/__init__.py, gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
Following the discussion on [1], Gnocchi was not properly handling the metric not found exceptions, which in turn causes a problem with Gnocchi client.
The exceptions were being rendered as a JSON, and not a string inside the description field. This PR fixes that.
The problem seems to have been caused by: https://github.com/gnocchixyz/gnocchi/commit/455c1b9b60942230028a6012a674c83816afd6ef
P.S. There are some other situations that the response is a JSON inside the description attribute. I would prefer as is and fix the issue in the Client. However, I see that this would break the backward compatibility.
[1] https://github.com/gnocchixyz/python-gnocchiclient/pull/133#discussion_r1084311700
=> Adjust metric not found exception

setup.cfg
Version 2 of SQL Alchemy has been released, and it brings considerable changes to it [1]. The one that is affecting us right away is the philosophy of always using a transaction. That means, for every connection open with the database (DB), there is automatically a transaction opened. This, in turn, breaks the current code structure that we have, where we try to open a transaction every time we get a connection to write or read in the DB. The break happens because the code is trying to open a transaction inside an already existing one (the transaction opened by SQL Alchemy itself).
This whole situation only happens with SQL Alchemy >=2. Therefore, for now, the solution is to pin down its (SQL Alchemy) version until we have a final solution, which is going to have a considerable impact in …
=> Pin down SQL Alchemy to <2

gnocchi/rest/aggregates/api.py, gnocchi/tests/test_aggregates.py, setup.cfg
With Python 3, the ``sort`` function is not handling `None` values. Therefore, when we handle resources with values as ``None`` an exception happens. This patch fixes such situations.
=> Fix issue with None value attributes

gnocchi/rest/app.py, gnocchi/rest/policies.py, setup.cfg
this will allow various oslo.policy scripts like
`oslopolicy-policy-generator` to work with Gnocchi.
Fixes: #1291
=> Add oslo.policy.enforcer entry point

images/Dockerfile.ci, setup.cfg, setup.py, tox.ini
This fixes multiple CI issues, see the commits.
=> Fix multiple CI issues

gnocchi/common/redis.py
The redis_url option can contain password string in case authentication is enabled in Redis, thus its value should be hidden in log output.
=> redis_url should be secret

gnocchi/common/redis.py
The socket_timeout argument of redis client supports not only integers
but also floats. This allows users to pass float values[1].
[1] https://github.com/redis/redis-py/blob/1b2f408259/redis/connection.py#L1206
=> Accept float values for socket_timeout

gnocchi/common/redis.py, releasenotes/notes/redis-ssl_ca_certs-c4908e78360a31fb.yaml
This change allows configuring ssl_ca_certs argument of redis client using the query parameter, so that users can use a specific CA certificates file instead of system global repository.
=> Allow using specific CA certificates file

releasenotes/notes/py36-support-removed-6d90f20b486e8441.yaml
Python 3.6 support is removed and Python 3.11
support is added. Minimum Python version is 3.8
or higher.
=> releasenote: add note about python 3.6 and 3.11

gnocchi/carbonara.py
```
DeprecationWarning: SplitKey.__float__ returned non-float (type numpy.float64)
```
=> carbonara: fix __float__ warning in SplitKey

bin/gnocchi-api, setup.cfg
We were wrapping easy_install's `install_scripts` and `develop` methods to generate a custom WSGI script. This was a replacement of functionality previously provided by PBR. Unfortunately easy_install is deprecated for removal at a future date and we don't yet have a modern equivalent in pip [1]. As such, we need a migration plan for this and it seems like the old school `scripts` option is probably it. The main downside of this is that the shebang isn't updated accordingly, which means this won't work very well in virtualenvs, but I'm hoping that the use of `/usr/bin/env` will allow us to work around this. At least in local testing, it seems like this is the case:
```
❯ virtualenv .venv
❯ pip install .
❯ cat .venv/bin/gnocchi-api | head -1
#!/gnocchi/.venv/bin/python
```
**EDIT**: this …
=> Drop use of setuptools extension

.github/workflows/gnocchi-ci-image.yml, .github/workflows/gnocchi.yml
Try to silence all the warnings about node12 and
save-state being removed.
=> ci: update actions to newest versions

tox.ini
The docs build fails because we've hardcoded this so docs is not updated.
See the build log here: https://gnocchi.osci.io/build-logs/gnocchi.log
See what we can do to rectify that, we don't know what version that runs.
This reverts commit cbf138eb4ffde968c168f3cfd8489db26a7a8dbb.
=> Revert "tox: use python3.9 for doc jobs"

setup.cfg
The http.parse_authorization_header is removed
in >=3.0.0 [1]
[1] https://github.com/pallets/werkzeug/commit/bafffa9fb597156567c1ca80042bfbc842a42284
=> Pin werkzeug<3.0.0

gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, setup.cfg
This was pinned in due to [1] error message
changing in pyparsing.
[1] https://github.com/pyparsing/pyparsing/issues/504
=> Unpin pyparsing

gnocchi/rest/auth_helper.py, setup.cfg
`parse_authorization_header` was removed here: https://github.com/pallets/werkzeug/commit/bafffa9fb597156567c1ca80042bfbc842a42284.
=> Update code for breaking change in werkzeug

doc/source/rest.j2, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/utils.py, releasenotes/notes/more_fill_options-7f2f1048d7cb097a.yaml
I'm not an expert in numpy, so this was borrowed from SO: https://stackoverflow.com/a/54508024.
I probably should rename this from "previous" to "similar" (or maybe some other better word?), as this thing covers the case when first point in resulting series could be NaN with backwards fill in addition to the standard forward fill. 
Fixes #1266
=> Add more fill variants

gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/test_rest.py
The commit https://github.com/alecthomas/voluptuous/commit/41bc53df12c078a2fc9ea586a280605c53db5ea1, which was introduced in version 0.14.0 of voluptuous library, improves the error messages for invalid keys. 
To make Gnocchi tests compatible with this new version, we need to update some error messages validation to use the newest error messages from voluptuous parser.
=> Update tests error messages to be compatible with voluptuous 0.14.0

gnocchi/json.py
The date manipulation in Gnocchi to generate the response  is quite odd, which is causing some weird outputs if the nanoseconds part of the string has some value different from .000000000; this patch is changing that to a better approach.
This was extract from https://github.com/gnocchixyz/gnocchi/pull/1307#discussion_r1330867035
=> Fix time format for datetime objects

gnocchi/common/redis.py, gnocchi/gendoc.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/indexer/sqlalchemy_extension.py, gnocchi/indexer/sqlalchemy_types.py, gnocchi/tests/functional/fixtures.py, setup.cfg
This module is buggy with Python 3.11 and 3.12, and is being actively removed from distributions (like Debian and Ubuntu). The absolute_import things are remaining of the past, in the Python 2.7 age. Let's get rid of them and remove future from setup.cfg.
=> Remove the use of the future module

doc/source/rest.j2
The `use_history` option for the aggregates API allows one to retrieve the exact attributes of a resource that were present during a given timestamp for a measurement obtained via the aggregates API. However, this API has a downside, which is the inability to execute "re-aggregations" for now. Therefore, if one needs to execute the "re-aggregation" of computed measures, she/he will need to use the aggregates API with the option `use_history` as `False`.
This patch makes that clear for the end users.
=> Improve documentation for aggregates API and the `use_history` option

gnocchi/opts.py
An option doesn't need to be marked required if it has a default value.
=> Drop redundant required property

gnocchi/common/redis.py
The socket_keepalive option in RedisClient is not an integer but a boolean. Also the healthcheck_interval option can accept not only integers but also float values. This fixes the types to parse these options accordingly.
Note this change still keeps support for socket_keepalive=1 or socket_keepalive=0 , but would remove support for the other integer values such as 2 or -1.
=> redis: Fix types of some options

gnocchi/common/redis.py
This fixes how the logic parses host and port from sentinel fallbacks when the host is IPv6 address. We should not use bare split by ':' because ':' is used within address representations like [::1]:6379.
=> Redis: Fix sentinel fallbacks with IPv6 address

gnocchi/common/redis.py, setup.cfg
Redis introduced ACL feature in 4.0.0, and this feature is supported by redis-py since 3.4.0[1]. When ACL is enabled, authentication requires username in addition to password.
[1] https://github.com/redis/redis-py/commit/8df8cd54d135380ad8b3b8807a67a3e6915b0b49
=> redis: Add username

gnocchi/indexer/sqlalchemy_types.py
... to resolve the warning from sqlalchemy.
=> Configure `cache_ok` for TypeDecorator implementation

gnocchi/common/redis.py
This change allows enabling SSL and/or authentication for redis sentinel. Previously both of these were possible for only redis, and connections to redis sentinel servers were not protected.
=> Support authentication and SSL for redis sentinel

setup.cfg
Some of the recent sqlalchemy 2 changes used features that were added in 1.4.24 sqlalchemy (session.scalar) [1]. This change fixes the issue with gnocchi-upgrade built with wrong constraints.
1. https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html#change-e619b9bd2796d7e0b948631fac5b01e9
=> Add minimum requirement for sqlalchemy to 1.4.24

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/indexer/sqlalchemy.py, gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_measures_grouper.py
Gnocchi aggregates API can present slowness with time, due to the growing number of resources and revisions in large scale OpenStack Cloud environments. This happens due to the situation where Gnocchi does not apply filters in the MySQL queries in the resource tables. I mean, start/stop filters are not applied, and others as well, which makes Gnocchi to manipulate all dataset in the MySQL database and then the filtering is executed in Python.
To cope with that situation, we are proposing an optimization to improve the query executed by Gnocchi in MySQL, and apply the filtering right away; thus, the dataset manipulated by MySQL will be drastically reduced. After applying the patch, we noticed a reduction of 5-6 folds in the response time for the Gnocchi aggregates API.
=> Optimize Gnocchi aggregates API

gnocchi/incoming/file.py
When running the upgrade command manually, we noticed that the "tmp" folder in the "conf.file_basepath" is not created, which will lead to an error later in the execution flow.
=> Fix Gnocchi manager upgrade command for File

gnocchi/storage/ceph.py
Before I describe the situation, let me put us all in the same page regarding the concepts we are dealing with. This patch is about the backend Ceph that can be used to store processed and raw measurements for Gnocchi. Ceph is a software defined storage, which when deployed implements a concept called Reliable Autonomous Distributed Object Store (RADOS). Do not confuse this RADOS with RadosGW, which is the sub-system that implements S3 API to consume a Ceph backend. In Ceph we have the RADOS objects, which are different from RadosGW objects (S3 objects).The RADOS objects depend on the underlying system that is consuming them; and, they (the RADOS objects) are the building blocks of any Ceph cluster. For instance, when using Rados Block Device (RBD), the libRBD or the KRBD use by default …
=> Address high IOPs usage of the Gnocchi Ceph pool

gnocchi/statsd.py, setup.cfg
The trollius library is required only in Python <= 3.4, but currently Python 3.8 is the minimum supported version.
=> Remove unused dependency

gnocchi/cli/api.py, gnocchi/cli/manage.py, gnocchi/cli/metricd.py, gnocchi/cli/statsd.py
When developing to Gnocchi, it is handy to run Gnocchi from Pycharm. To achieve that, if we have the main methods already in the CLI modules, one can easily start Gnocchi directly from Pycharm in Debug mode. Therefore, this patch introduces such option
=> Add main to CLI classes

gnocchi/cli/api.py, gnocchi/opts.py
In some cases, we might need to override the uWSGI path. Therefore, a configuration for the operator to execute such configuration is interesting to have in hand.
=> Enable custom uWSGI path

gnocchi/chef.py, gnocchi/cli/api.py, gnocchi/cli/metricd.py, gnocchi/incoming/file.py, gnocchi/indexer/__init__.py, gnocchi/indexer/alembic/versions/18fff4509e3e_create_column_for_truncate_inactive_metrics_process.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/opts.py, gnocchi/rest/api.py, gnocchi/rest/app.py, gnocchi/rest/auth_helper.py, gnocchi/service.py, gnocchi/storage/__init__.py, run-upgrade-tests.sh
The truncating of the raw metrics data is only done when new measures are pushed. Therefore, if no new measures are pushed, and the archive policy is updated to reduce the back window, the raw data points for metrics that are not receiving new data points are never truncated.
The goal of this PR is to propose a method to identify metrics that are in "inactive state", meaning, not receiving new data points, and execute their raw data points truncation when the archive policy backwindow is changed.
=> Clean raw data metrics that do not receive measures

images/Dockerfile.ci
we get a collision because jaraco.text is installed in site-packages but we want a newer version when
testing.
werkzeug dist package in ubuntu works with python 3.10 but not 3.9, this fixes that, the hack can be removed when we drop 3.9 support
=> image: hack jaraco.text and werkzeug to fix CI

setup.cfg, tox.ini
Now that pifpaf 3.2.0 is released we can
stop pinning it and unpin it completely.
=> Unpin pifpaf

gnocchi/indexer/sqlalchemy_base.py
Replace usage of the deprecated backref option [1] and implicit relationship population, with the new back_populates [2] option and explicit relationship definitions on both the Metric and Resource classes.
This eliminates "AttributeError: type object 'Metric' has no attribute 'resource'" exceptions that can occur when Metric.resource is referenced using sqlalchemy.orm.joinedload in queries.
This change is backwards compatible with SQLAlchemy 1.4.
1: https://docs.sqlalchemy.org/en/20/orm/backref.html
2: https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html
=> Switch Metric-Resource relationship to back_populates

gnocchi/rest/auth_helper.py, gnocchi/rest/policies.py
The next release of oslo.policy enables scope check by default. To adopt to the new release, add scope_types definition to all policy rules.
=> Add explicit scope types for all policies

gnocchi/rest/aggregates/api.py
The use of the start/end filtering in resources listage in the aggregates api was generating an undesired behavior that was not showing measures of resources when the measures timestamp were from before the resources start time, which were displayed before this filter was introduced. This patch restores the old behavior.
To achieve the current filtering behavior, now the users must explicitly apply these start/end filtering in the "search" 
parameter in the aggregates query.
=> Remove the start/end filtering from aggregates resource query

gnocchi/common/redis.py
This change allows enabling SSL and/or authentication for redis sentinel. Previously both of these were possible for only redis, and connections to redis sentinel servers were not protected.
Backports: https://github.com/gnocchixyz/gnocchi/pull/1376
(cherry picked from commit 20e596456e850578df753a89b55e22693ab813f5)
=> Support authentication and SSL for redis sentinel (backport #1376)

gnocchi/common/redis.py
Hi,
The `_parse_sentinel` was a class function and when it get called by
```
sentinel_hosts = [
_parse_sentinel(fallback)
for fallback in kwargs.pop('sentinel_fallback', [])
]
```
It made errors because it doesn't pass cls to it and it can't receive the sentinel.
So I made it static and tested it and its OK now.
=> Function call issue for parsing sentinel_fallback

tox.ini
It seems the setuptools library is no longer installed by default.
Co-Authored-By: @kajinamit
(cherry picked from commit 74c81c79c57fbccdea55b056e3edb6a5e425e0d9)
=> Install setuptools

gnocchi/__init__.py, gnocchi/opts.py, gnocchi/rest/app.py, setup.cfg
... because it was removed in Python 3.12 [1].
[1] https://docs.python.org/3/whatsnew/3.12.html#ensurepip
=> Get rid of pkg_resources

gnocchi/cli/api.py, gnocchi/common/redis.py, gnocchi/rest/api.py, gnocchi/tests/test_rest.py, gnocchi/utils.py
The distutils module was removed from Python 3.12 .
=> Get rid of distutils

gnocchi/common/redis.py, setup.cfg
The oslo.utils library is already required via some of the current dependencies (eg. tooz). Use the utility method from it to parse host:port format instead of carrying our own method.
=> Use oslo.utils method to parse server format

.github/workflows/gnocchi.yml, .mergify.yml, images/Dockerfile.ci, images/entrypoint.sh.ci, tox.ini
* Use Ubuntu 24.04 LTS for Docker image
* Add testing for Python 3.12 (we now test 3.9, 3.11 and 3.12)
* We still don't test Ceph jobs (they have been disabled for a while due to rados timeouts) – this needs to be fixed in the future
* Install virtualenv from disto package
* Use a virtualenv for tox to not interfere with distro
* Use my Pifpaf fork that includes commit https://github.com/tobias-urdin/pifpaf@2d0890b7efb7af50172a95e5065a51d7871e8a76 because Ubuntu 24.04 LTS packages Ceph 19.2.0 with a version containing a `~<git commit>` suffix that packaging doesn't like, this is because Ubuntu packaged Ceph 19.2.0 before it was released officially
* Pin hacking to a newer version so that we get atleast 7.0.0 that has Python 3.12 support
=> Test Python 3.12 on Ubuntu 24.04 LTS

tox.ini
A few directories (expecially build) may include files which cause undesired errors.
=> flake8: excludes more directories

tox.ini
The 3.2.2 release of pifpaf includes the
Ceph fix that we need.
This reverts commit a537a58ad8d735ada17bd7c96a6cf3f2b0a24ec2.
=> Revert "Use custom pifpaf"

gnocchi/incoming/swift.py, gnocchi/storage/swift.py, gnocchi/tests/base.py, releasenotes/notes/swift-storage-policy-fa2d73d8714e3a03.yaml
This adds the `swift_storage_policy` configuration option for setting the storage policy Gnocchi will use when creating new Swift containers.
When unset the storage policy will not be configured when creating containers, in which case Swift will use the default storage policy.
=> Swift: Allow configuring container storage policies

.github/workflows/gnocchi.yml, images/Dockerfile.ci, images/entrypoint.sh.ci, tox.ini
Fix CI image build issues that made certain hacks necessary for things to work, and remove hacks that are no longer required with the new Ubuntu 24.04-based CI image.
* Use the Ubuntu-packaged version of Tox, Setuptools and and all other packages installed outside of the test environment. This is necessary to make dependency conflicts less likely due to setting `sitepackages` to `True` in Tox to pass through `python3-rados` to the test environment.
* Remove the hack for deleting the distro-managed version of `pyparsing`, as the new version available in Ubuntu 24.04 is compatible.
* Remove the hack for deleting the distro-packaged versions of the `jaraco.*` series of packages. The reason why this started causing problems is [Setuptools …
=> Remove CI image build hacks

setup.cfg
Python 3.8 already reached its EOL and was removed from test coverage.
=> Bump minimum python version

gnocchi/cli/api.py, setup.cfg
oslo.policy 4.5.0[1] changed the default value of `[oslo_policy] policy_file` to use yaml file by default.
[1] https://opendev.org/openstack/oslo.policy/commit/26b04a4a803b21f8dc5ea7e3bc6ca76bf3144cfc
=> Remove default override for policy_file option

gnocchi/tests/test_carbonara.py
`testcase` performs an `if not` check on annotations passed in asserts.
From NumPy 2.2 this raises an exception about ambiguous falseyness [1], so convert the array to a string when passing it as an annotation to get around this.
[1]: https://numpy.org/devdocs/release/2.2.0-notes.html#expired-deprecations
=> Fix running functional tests with NumPy 2.2

gnocchi/resource_type.py, gnocchi/tests/functional/gabbits/resource-type.yaml, releasenotes/notes/string-attribute-max-length-33e037494a0e318c.yaml
Increase the maximum supported length for string type resource attributes from 255 to 256 characters, to allow creating string attributes on resources that accept values of such length (e.g. Swift container names).
=> Increase string attribute max length to 256 chars

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/indexer/__init__.py, gnocchi/indexer/alembic/versions/f89ed2e3c2ec_create_last_measure_timestamp_column.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/opts.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, gnocchi/tests/indexer/sqlalchemy/test_migrations.py, run-upgrade-tests.sh
This patch is created on top of https://github.com/gnocchixyz/gnocchi/pull/1385, https://github.com/gnocchixyz/gnocchi/pull/1381,  https://github.com/gnocchixyz/gnocchi/pull/1387, and https://github.com/gnocchixyz/gnocchi/pull/1388. Therefore, we need to merge them first. Then, the extra commits here will disappear.
While executing some Gnocchi optimizations (https://github.com/gnocchixyz/gnocchi/pull/1307), we noticed that some deleted/removed resources do not have the "ended_at" field with a datetime. This can cause slowness with time, as more and more "zombie" resources are left there, and this has a direct impact in the MySQL queries executed with the aggregates API.
This patch introduces a new parameter called `metric_inactive_after`, which defines for how long a metric can go …
=> Automatically detect deleted resources

gnocchi/rest/api.py, gnocchi/rest/auth_helper.py, gnocchi/tests/test_rest.py
When using a minimal RBAC policy that only allows either access either to a cloud admin or a user that is part of the project a metric's resource is owned by, e.g.
```yaml
"list metric": "role:admin or project_id:%(resource.project_id)s"
```
There is an issue where `KeystoneAuthHelper.get_metric_policy_filter` will reject access to the metrics because from its perspective there are no applicable policies that the user has permission under.
This patch fixes that by adding an option to `get_metric_policy_filter` that allows an empty policy filter to be returned if an enforcement check for `resource.project_id` passes. This option is set to `False` by default, and only enabled where necessary.
This allows the caller to use `KeystoneAuthHelper.get_resource_policy_filter` to add project …
=> Fix listing metrics as non-admin without creator policy defined

gnocchi/rest/aggregates/api.py, gnocchi/rest/api.py, gnocchi/tests/test_rest.py
When using the aggregates API with a metric ID, the RBAC policy `project_id:%(resource.project_id)s"` fails to authenticate a non-admin user that is part of the project the metric is also part of via its resource relationship.
This patch fixes two issues preventing this from working:
* Set `details=True` when listing specified metrics to ensure the joined load with the `Metric` and `Resource` models is done.
* Add support for processing oslo.db SQLAlchemy models in `gnocchi.rest.api.flatten_dict_to_keypairs` to make sure nested attributes are added to the list of targets passed to the policy enforcer.
=> Fix metric aggregates as non-admin

gnocchi/rest/policies.py, releasenotes/notes/service-role-ffc61f0a1d1de20d.yaml
This adds support for the service role that is
used in the Secure RBAC community goal in OpenStack.
This is matched against what API calls that Ceilometer
and Aodh does against the Gnocchi API.
=> Support service role

gnocchi/tests/test_utils.py, gnocchi/utils.py
`to_timestamps()` can convert string datetimes to `np.datetime64` objects. The timestamp values can have a timezone set on them, but `np.datetime64` types do not store the timezone. Converting these timestamp values results in a warning being logged.
These timestamps are converted to UTC by numpy before changing the type to `np.datetime64`, which is what we intend to happen here. Silence the warnings due to timezone information being discarded.
Also add some missing unit tests for `to_timestamps()` to make sure timezone conversion is being done.
Fixes #1464.
=> Suppress np.datetime64 timezone warnings

gnocchi/indexer/sqlalchemy_base.py
Set `overlaps="metrics,resource"` on the `ResourceHistory.metrics` relationship defining a one-to-many relationship between resource history columns and metrics mapped to the resource.
This lets SQLAlchemy know to expect an overlap for the relationships between `Metric`, `Resource` and `ResourceHistory`, suppressing a warning output when the table schema is loaded. Because `back_populates` is configured to go between `Metric` and `Resource`, `ResourceHistory` rows should not be returned when `Metric.resource` is used.
Fixes #1406.
=> Define ResourceHistory.metrics relationship overlap

gnocchi/wsgi/api.py
... so that API can be loaded using the module path, instead of the script file.
=> Add wsgi module

gnocchi/json.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
Some aggregates operations (e.g. `=`) return a `numpy.bool` object, and it is possible to get Gnocchi to return these, but the JSON encoder fails to encode them correctly.
This could be useful for some aggregations (e.g. checking status of OpenStack resources is a specific value), so add support to `gnocchi.json.to_primitive` for encoding `numpy.bool` to a floating-point number so it can be returned in aggregates queries as a `numbool`-style value.
Fixes #1473.
=> Support returning boolean aggregates
