tox.ini
=> Remove requirement comments

doc/source/install.rst
doc: add incoming configuration option note
=> Merge request for jd/add-incoming-in-doc

devstack/plugin.sh, devstack/settings
This change updates devstack to use Grafana 4
Change-Id: I2d7ca78f7d7c2d77eb2c53c25851a088d6fbd1c1
=> Uses Grafana 4

gnocchi/storage/incoming/redis.py
pipeline allows us to group multiple actions in a single request
saving roundtrip of multiple requests. this is at expense of
immediate feedback but since we don't give feedback per measure in
batch, this doesn't matter.
in testing with 20metric batch POST, this improves performance by ~15%.
closes https://github.com/gnocchixyz/gnocchi/issues/18
=> use pipeline to batch push measures

devstack/README.rst, devstack/plugin.sh, doc/source/install.rst
point to new gnocchixyz project
=> cleanup devstack

gnocchi/cli.py
i missed removing this when i dropped scheduler process. there is no more internal queue.
=> remove residual queue

doc/source/conf.py, gnocchi/indexer/alembic/script.py.mako
drop openstack copyright templating
=> change copyright template

gnocchi/storage/incoming/swift.py, gnocchi/tests/test_storage.py
swift is reporting double the real number of metrics in backlog
=> fix swift slim reporting

gnocchi/archive_policy.py, gnocchi/tests/gabbi/gabbits/archive.yaml, gnocchi/tests/test_archive_policy.py
archive_policy: Raise Error if calculated points is < 0
=> archive_policy: Raise Error if calculated points is < 0

doc/source/contributing.rst
doc: add a note on pull-requests
doc: fix issue tracker link not being in RST
=> Improve contributing docs

.travis.yml
=> Fix doc build

gnocchi/rest/__init__.py, gnocchi/storage/__init__.py, gnocchi/storage/_carbonara.py, gnocchi/storage/ceph.py
storage: introduce add_measures_batch for Ceph
=> storage: introduce add_measures_batch for Ceph

gnocchi/carbonara.py
leftover from v2 upgrade path.
=> drop unused _timestamps_and_values_from_dict method

.gitreview
Change-Id: Id779145bb9dfc95237ba89b131536d9408bec811
=> Remove gitreview config

run-upgrade-tests.sh
Calling 28800 times `date' is pretty slow. Let's generate that data in a snap
using Python.
=> tests: speed-up data generation

.travis.yml, tox.ini
That'll simplify the dev workflow and Travis jobs number.
=> Merge pep8 and bashate jobs

gnocchi/tests/functional/fixtures.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/archive-rule.yaml, gnocchi/tests/functional/gabbits/archive.yaml, gnocchi/tests/functional/gabbits/async.yaml, gnocchi/tests/functional/gabbits/base.yaml, gnocchi/tests/functional/gabbits/batch-measures.yaml, gnocchi/tests/functional/gabbits/history.yaml, gnocchi/tests/functional/gabbits/metric-granularity.yaml, gnocchi/tests/functional/gabbits/metric-list.yaml, gnocchi/tests/functional/gabbits/metric-timestamp-format.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/functional/gabbits/pagination.yaml, gnocchi/tests/functional/gabbits/resource-aggregation.yaml, gnocchi/tests/functional/gabbits/resource-type.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search-metric.yaml, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/functional/gabbits/transformedids.yaml
Since noauth is deprecated, rewrite the tests using the basic auth
=> gabbi: upgrade test to basic authentication instead of noauth

doc/source/releasenotes/4.0.rst, doc/source/releasenotes/index.rst
=> doc: add release note for 4.0

devstack/plugin.sh
leverage GNOCCHI_BIN_DIR like every other place.
=> dynamically set bin path

setup.cfg, tox.ini
=> Install gnocchi flavor of pifpaf

gnocchi/common/swift.py, gnocchi/storage/swift.py
Add following missing configurations:
* swift_auth_insecure
* swift_cacert
* swift_region
* swift_service_type
=> Add missing configs for Swift storage

gnocchi/cli.py
=> Make compatible with tenacity<4.0.0

requirements.txt
=> Update tenacity requirement to 4.0.0

gnocchi/carbonara.py
pandas naturally stores index as np.array(dtype='datetime64[ns]')
=> use pandas index values

gnocchi/carbonara.py
=> carbonara: remove outdated comment

gnocchi/carbonara.py
we don't need math to build a hash
=> simplify hashing

gnocchi/rest/__init__.py
The JSON encoder knows how to format properly datetime objects.
=> rest: return timestamp without conversion

gnocchi/service.py, gnocchi/tests/base.py
Other than that the tests are only running using WARNING.
=> tests: set logging level to debug when setting GNOCCHI_TEST_DEBUG

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/test_indexer.py
When we use the ne operator, row with NULL values are not returned by
mysql or postgresql.
This change fixes the sql query to return them.
Closes #224
=> indexer: fix ne operator

doc/source/operating.rst
In section plan Gnocchi's storage, there is a little mistake in the
example, so fix it.
=> Modify a mistake in plan Gnocchi storage

gnocchi/incoming/ceph.py
The class is in gnocchi.incoming, not gnocchi.incoming._carbonara
=> ceph: fix ReportGenerationError raise

gnocchi/aggregates/moving_stats.py, gnocchi/carbonara.py, gnocchi/storage/_carbonara.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_statsd.py, gnocchi/tests/test_storage.py, gnocchi/utils.py
carbonara: remove weird key check
Remove most of Pandas usage from Carbonara
=> Pull request for use-numpy-in-carbonara

gnocchi/rest/__init__.py, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/test_rest.py
Resource search allow to pass the query in "filter" query string option.
Batch delete API is identical to resource search API.
So this change allows this filter option too.
=> rest: allow filter= for batch delete

gnocchi/rest/__init__.py
=> rest: fix docstring for strtobool

gnocchi/resource_type.py, gnocchi/tests/functional/gabbits/resource-type.yaml
=> rest: fix error message UUID attribute validation in resource type

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/carbonara.py, gnocchi/rest/__init__.py, gnocchi/rest/transformation.py, gnocchi/storage/__init__.py, gnocchi/storage/_carbonara.py, gnocchi/tests/functional/gabbits/aggregation.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/test_carbonara.py, gnocchi/tests/test_storage.py, gnocchi/tests/test_transformation.py, releasenotes/notes/tranform-API-da38b196c1c72d44.yaml
Allow to transform measures
use map instead of enumeration
=> Allow to transform measures (absolute, negative, resample)

doc/source/rest.j2
doc: split measure sections
doc: add rate of change in aggregations list
=> Pull request for sileht/doc

doc/source/rest.j2
basic auth requires Base64 encoding
Closes #316
=> add note regarding basic auth encoding

doc/source/running.rst
(cherry picked from commit bdb9a9a94b487e2c25368359dcdb75e4e9da4511)
=> doc: fix formatting issues in default archive policies list

.travis.yml
This is a hack to quickly exists useless jobs.
=> travis: don't build merge push

doc/source/rest.j2, doc/source/rest.yaml
=> Add documentation for delete-metric API

gnocchi/statsd.py
=> statsd: don't fetch resource on each flush()

gnocchi/indexer/sqlalchemy.py
=> Apply archive policy rules by name order

requirements.txt
we use wraps which was added in 4.2.0
https://github.com/jd/tenacity/commit/913aff6604d75ff28576ae7793ef3d57cfd17029
=> bump tenacity req

gnocchi/tests/test_cross_metric.py
- test to ensure we always derive boundaries if not provided
- test to verify derive boundary is always set to first and last
overlap
- test to verify derive boundary if only provided start or stop.
=> more tests for cross metric aggregation

gnocchi/incoming/__init__.py, gnocchi/indexer/__init__.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/rest/api.py, gnocchi/statsd.py, gnocchi/storage/__init__.py, gnocchi/tests/base.py, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_cross_metric.py, gnocchi/tests/test_incoming.py, gnocchi/tests/test_storage.py, tools/measures_injector.py
Measure is only leveraged by incoming driver.
=> move Measure model to incoming and Metric to indexer

gnocchi/cli/metricd.py
metricd: fix coordinator not implemented error
metricd: be specific about tooz.NotImplemented
=> Pull request for metricd-not-implemented-sacks

gnocchi/rest/api.py, gnocchi/tests/test_rest.py
=> rest: expose the gnocchi build

doc/source/install.rst
Commit 07f770aeaed3192b446e3e0aa5a2e66a8fe6931b simplified flavor lists but
forgot the doc.
=> doc: update flavor list

gnocchi/rest/api.py
api: convert exceptions JSON data struct rather than just a string
api: remove abort unused extra arguments
=> Pull request for jsonify-exceptions

gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-fetch.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/test_aggregates.py, gnocchi/tests/test_rest.py
=> aggregates: fetch api

gnocchi/rest/aggregates/operations.py
support rolling window over 2d array
=> rolling window over matrix

gnocchi/rest/aggregates/processor.py, gnocchi/tests/test_aggregates.py
don't try to compute overlap if empty
=> return empty series if empty series given

gnocchi/common/redis.py
There's is a python-redis on PyPI, and that's not what we want.
Let's not be confusing.
=> redis: enhance error message is redis is not installed

gnocchi/indexer/__init__.py, gnocchi/indexer/sqlalchemy.py, gnocchi/rest/aggregates/api.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_indexer.py, gnocchi/tests/test_storage.py
indexer: replace ids argument with attribute filter in list_metrics()
indexer: replace names filter in list_metric by attribute_filter
indexer: replace kwargs filtering by regular attribute filter
=> Pull request for metric-list-attribute-filter

gnocchi/common/redis.py, gnocchi/opts.py, gnocchi/storage/redis.py
=> redis: add documentation for the url

gnocchi/rest/aggregates/api.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml
=> aggregates: catch indexer exception

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/aggregates/api.py, gnocchi/rest/aggregates/processor.py, gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml, releasenotes/notes/aggregates-metric-wildcard-d489260c685c5727.yaml
aggregates: allow wildcard as metric name
=> aggregates: allow wildcard as metric name

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/test_indexer.py
=> indexer: do not return empty IN statement in QueryFilter

gnocchi/indexer/__init__.py, gnocchi/indexer/sqlalchemy.py, gnocchi/rest/api.py, gnocchi/rest/auth_helper.py, gnocchi/tests/test_indexer.py, gnocchi/tests/test_rest.py
rest: use resource_policy_filter when listing metrics
indexer: add support for resource_filter in list_metrics
indexer: add a policy_filter on list_metrics
=> Pull request for rest-metric-list-keystone

setup.cfg
Last keystonemiddleware have some missing dependencies
Ban this version for now
=> Ban keystonemiddleware 4.19

.travis.yml, gnocchi/gendoc.py
This change fix the py2/py3 unicode issue.
Also, it disables temporary the docs-gnocchi.xyz jobs, because
we can't generate the master branch doc anymore.
=> doc: fix py2/3 unicode issue

gnocchi/gendoc.py
This change ensure the doc build fail if something goes wrong with the
multiversion hack.
=> doc: fail if something go wrong with the hack

gnocchi/carbonara.py
this isn't that much faster based on benchmark but it's less work.
=> append once when merging

doc/source/prometheus.rst, gnocchi/rest/api.py
Prometheus: job and instance are not mandatory
prometheus: no need to sanitize /
=> Pull request for sileht/doc-prom

gnocchi/carbonara.py
- vectorize std. ~35x faster
- use bincount+weights to compute sum. ~1.7x faster
- use sum to get mean. ~1.6x faster
- insert creates a copy. just flip array to get first. ~1.1x faster
=> optimise aggregations

gnocchi/rest/app.py, gnocchi/tests/functional/fixtures.py, gnocchi/tests/test_rest.py
When of the backend are unreachable, the error is differ depending
of if the issue occurs on startup or at runtime.
This change ensures any error are raised at runtime.
Closes-bug: #585
=> rest: lazy load backends

gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/test_storage.py
This cleans a bit the old search_value/find_measure storage API to do most of
the API related work in the API, and only do the minimum work in the storage
part.
=> storage: rework search_value

doc/source/rest.yaml, gnocchi/indexer/alembic/versions/1c98ac614015_initial_base.py, gnocchi/indexer/alembic/versions/27d2a1d205ff_add_updating_resource_type_states.py, gnocchi/indexer/alembic/versions/5c4f93e5bb4_mysql_float_to_timestamp.py, gnocchi/indexer/sqlalchemy.py, gnocchi/indexer/sqlalchemy_base.py, gnocchi/indexer/sqlalchemy_extension.py, gnocchi/indexer/sqlalchemy_types.py, gnocchi/resource_type.py, gnocchi/tests/functional/gabbits/resource-type.yaml, releasenotes/notes/datetime-resource-attribute-type-1e627a686568f72a.yaml, setup.cfg
This change adds a new type of attribute for resource: datetime.
=> Add datetime for resource attribute type

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
redis: implement batched _get_measures
storage: make _get_measures batched
=> Batched measures retrieval

gnocchi/carbonara.py
numpy.insert takes a created array and inserts accordingly in a
new array. numpy is actually faster if you just declare things
up front and set the type. this drops numpy.insert usage and
improves:
- compressed serialisation: 5%-20%
- uncompressed serialisation: 5%-10%
- bounded serialisation: 5%-10%
timeit a = numpy.empty(arr.size + 1); a[1:] = arr; a[0] = 123*23/1
1000000 loops, best of 3: 921 ns per loop
timeit a = numpy.insert(arr, 0, 123*23/1)
100000 loops, best of 3: 6.3 µs per loop
timeit a = numpy.empty(arr.size + 1); a.fill(123*23/1); a[1:] = arr
1000000 loops, best of 3: 1.11 µs per loop
timeit a = numpy.full(arr.size + 1, 123*23/1); a[1:] = arr
1000000 loops, best of 3: 1.78 µs per loop
=> declare expected array instead of insert

tox.ini
=> doc: fix gnocchi.xyz for stable/3.? by setting a tiny range for lz4

.travis.yml
(cherry picked from commit 3a6afc17fd3c46bc4c51a396d608da8a1e500fad)
=> doc: do not test gnocchi.xyz build on stable branch

gnocchi/service.py
=> service: log version number at startup

gnocchi/indexer/sqlalchemy.py, gnocchi/tests/functional/gabbits/search.yaml
The not operator was buggy. This change fix it.
Closes: #649
=> indexer: fix not operator

gnocchi/common/ceph.py
=> ceph: understandable error on misconfiguration

gnocchi/cli.py
metricd: restart scheduler on group membership issue
cli: fix error message string formatting
=> Pull request for rejoin-on-fail

gnocchi/cli.py
metricd: stop coordinator on membership issue
metricd: restart scheduler on group membership issue
=> Pull request for stable-3.1-fix-coord-unsync

gnocchi/common/redis.py
=> redis: make socket_timeout optional

doc/source/rest.j2
Add information about the special handling of resource ids.
Closes #698
=> update documentation regarding resource ids

gnocchi/rest/api.py, gnocchi/tests/test_rest.py
=> rest: load metric details for ACL

doc/source/influxdb.rst, gnocchi/cli/api.py, gnocchi/opts.py, gnocchi/rest/app.py, gnocchi/rest/influxdb.py
uwsgi: fix freeze, http/1.1 and keepalive
uwsgi: --thunder-lock doesn't take param in cmd
=> uwsgi: fix freeze, http/1.1 and keepalive

gnocchi/storage/__init__.py
- fix formatting
- we don't lock metrics in v4.x
=> cleanup storage exceptions

gnocchi/storage/redis.py
redis: use a Lua script to get measures
redis: create metrics using a single hsetnx() operation
redis: batch new measures retrieval with a Lua script
redis: use a Lua script to list split keys
=> Pull request for redis-lua

gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/storage/__init__.py
This patches rename the context manager process_measure_for_metric to
process_measure_for_metrics as it now yields a dict of several metrics at the
same time.
=> incoming: batch incoming measures retrieval

gnocchi/chef.py, gnocchi/cli/metricd.py, gnocchi/storage/__init__.py, gnocchi/tests/test_chef.py, gnocchi/tests/test_storage.py
Some of the code is currently tied to the Storage driver, whereas it interacts
with many other components. This should be moved out.
That patch introduces the Chef, a class responsible for doing complex actions
that require interactions and orchestrations with different actors.
=> Add Chef class to orchestrate complex actions

gnocchi/cli/manage.py, gnocchi/cli/metricd.py, gnocchi/incoming/__init__.py, gnocchi/incoming/ceph.py, gnocchi/incoming/file.py, gnocchi/incoming/redis.py, gnocchi/incoming/s3.py, gnocchi/incoming/swift.py, gnocchi/tests/base.py, gnocchi/tests/test_incoming.py, gnocchi/tests/utils.py
Rather than manipulating integers, let's use a Sack object to abstract properly
our sack concept. This cleans the code in various places.
=> incoming: introduce a Sack object

gnocchi/tests/functional/fixtures.py
Currently 'file' is hardcoded in gabbit tests. This change
uses the spawn driver instead.
=> tests: run functional tests on real backends

gnocchi/carbonara.py
Gnocchi might creates a lot of those, let's make them small.
=> carbonara: use __slots__ on SplitKey

doc/source/contributing.rst
=> doc: add more doc on pull-request and Pastamaker

gnocchi/storage/__init__.py, gnocchi/storage/ceph.py, gnocchi/storage/file.py, gnocchi/storage/redis.py, gnocchi/storage/s3.py, gnocchi/storage/swift.py, gnocchi/tests/test_storage.py
This should help to limit the number of calls make to list_split_keys in the
future.
=> storage: list_split_keys can now list several aggregations at once

run-tests.sh
=> tests: Ensure signal are propagated to subshell

gnocchi/incoming/file.py
The current code only delete one metric files :(
=> storage/file: fix new incoming measures deletion

gnocchi/tests/test_storage.py
=> expand test to validate measures are deleted

gnocchi/storage/__init__.py
This factorize the call to _list_split_keys() so all aggregations that needs
the list of keys are retrieved in just one call.
=> storage: do all listing for all aggregations at once in _add_measures

gnocchi/storage/__init__.py
This makes sure that all operations are batched, including the _list_split_key
that is now done only once for a metric!
=> storage: merge all _compute_split_operations calls into one

gnocchi/incoming/ceph.py
This allows to return a dict that can be used by process_measure_for_metrics
=> ceph: change list_keys_to_process to return values

gnocchi/cli/metricd.py, gnocchi/rest/api.py, gnocchi/storage/__init__.py, gnocchi/tests/functional/gabbits/base.yaml
=> metricd: publish statistics about processing speed

setup.py
pbr 4 broke compatibility with hooks.
Fixes #838
=> Cap pbr to <4

gnocchi/chef.py
bail early if we know there's no work to be done.
=> don't do work if no measures

setup.cfg
see: Pylons/webob#355
Closes: #852
=> ignore webob 1.8.0, it's broke

requirements.txt
=> Cap WebOb to <1.8.0

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/aggregates/api.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/history.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/test_rest.py, releasenotes/notes/remove-options-in-accept-header-7e5e074d8fccfb0f.yaml, setup.cfg, tox.ini
See https://github.com/Pylons/webob/issues/355
=> api: remove parameter passing via Accept header

gnocchi/chef.py, gnocchi/incoming/__init__.py
This can be leveraged by the Chef to group the metrics by sack as it wishes.
=> incoming: provide group_metrics_by_sack method

gnocchi/cli/metricd.py
=> metricd: fix typo in update_capabilities

gnocchi/cli/injector.py
This removes unused method. And fixup the logging issue
due to the shallowed "metrics" variable.
=> injector: cleanup

gnocchi/storage/file.py
(cherry picked from commit 30d865e2b2c94ebf7884927bf9c2d849d29eed91)
=> file: move directory creation in the upgrade path, not init

setup.cfg
remove workaround... or we can hit revert on original
=> new requests lib released

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/rest/aggregates/api.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/history.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/test_rest.py, releasenotes/notes/remove-options-in-accept-header-7e5e074d8fccfb0f.yaml, requirements.txt
This reverts commit 106bd4e4b24810dad06b95582f2a0a903ae35d98.
=> Revert "Cap WebOb to <1.8.0"

doc/source/rest.j2, doc/source/rest.yaml, gnocchi/calendar.py, gnocchi/carbonara.py, gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/resample-calendar.yaml, gnocchi/tests/test_calendar.py, releasenotes/notes/calendar-groups-1336b6d097c01b64.yaml
support ability to group by year, half, quarter, month, and week.
=> support resampling on calendar dates

tox.ini
=> Remove unused tox venv

gnocchi/common/redis.py
=> redis: fix sentinel Lua script registrations

gnocchi/storage/__init__.py
Change-Id: I9747a9bc9f9adea61bb6bcca571aa90c473172d5
=> Fix splits update statistics dictionary key

gnocchi/rest/api.py, gnocchi/tests/functional/gabbits/aggregates-with-metric-ids.yaml, gnocchi/tests/functional/gabbits/archive-rule.yaml, gnocchi/tests/functional/gabbits/archive.yaml, gnocchi/tests/functional/gabbits/metric.yaml, gnocchi/tests/functional/gabbits/resource-type.yaml, gnocchi/tests/functional/gabbits/resource.yaml, gnocchi/tests/functional/gabbits/search.yaml, gnocchi/tests/functional_live/gabbits/live.yaml, gnocchi/tests/test_rest.py, releasenotes/notes/api-user-input-invalid-09b045f5ab12c.yaml
/!\ WIP ONLY
Related to https://github.com/gnocchixyz/gnocchi/issues/195
=> improve 4xx voluptuous message

gnocchi/cli/metricd.py
catch and carry on.
Closes: #996
=> ignore update_capabilites if unsupported

README.rst, setup.cfg
seems long_description needs to render cleanly to upload to pypi:
https://github.com/pypa/warehouse/issues/5890
related: #1025
=> cleanup README.rst to upload to pypi

.travis.yml, doc/source/install.rst, gnocchi/common/ceph.py
Update the docs etc. to use rados directly.
=> cradox is not supported anymore.

.travis.yml, doc/source/conf.py, doc/source/contributing.rst, gnocchi/cli/injector.py, gnocchi/common/ceph.py, gnocchi/indexer/alembic/versions/5c4f93e5bb4_mysql_float_to_timestamp.py, gnocchi/indexer/alembic/versions/aba5a217ca9b_merge_created_in_creator.py, gnocchi/rest/api.py, gnocchi/tests/base.py, gnocchi/tests/functional/gabbits/resource-type.yaml, gnocchi/tests/test_rest.py, run-upgrade-tests.sh, setup.cfg, tox.ini
=> Fixes to CI for stable/4.3

.mergify.yml
so it matches github action job name
=> fix mergify job names

run-func-tests.sh
It should support Python 3 now
=> Enable Swift tests

.github/workflows/gnocchi.yml
When updating the Dockerfile or entrypoint.sh script used for CI image build the image, test with it so that we don't merge changes in the blind.
=> Test CI image when changed

.github/workflows/gnocchi.yml
(cherry picked from commit 41b7331a1e43d87626652d1fc268d240b75bea44)
=> ci: run tests with new image if it's changed

gnocchi/cli/api.py, setup.cfg
This reverts commit a53fcfc3ab60be6e223712d46e050e8740f16c23.
=> Revert "Fix incomplete switch to policy.yaml"

images/Dockerfile.ci, setup.cfg, setup.py, tox.ini
This fixes multiple CI issues, see the commits.
=> Fix multiple CI issues

gnocchi/indexer/sqlalchemy.py
this is available since 4.15.0 and our
minimum oslo.db version is higher than that.
=> db: fix todo in enginefacade

.github/workflows/gnocchi.yml, gnocchi/gendoc.py, gnocchi/rest/aggregates/operations.py, gnocchi/rest/aggregates/processor.py, setup.cfg, setup.py, tox.ini
Fix CI for stable/4.5 branch and remove upgrade testing from 4.4 as we will test upgrades from 4.5 now.
=> Fix CI for stable/4.5
